//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for IdentifyItemUseView.
/// </summary>
public class IdentifyItemUseView : BaseView
{
	public GameObject EmptyInfo;
	public UILabel CountLabel;
	public UILabel DecLabel;
	public UILabel EquipmentTipLabel;

	public void Setup (Transform root)
	{
		EmptyInfo = root.Find("EmptyInfo").gameObject;
		CountLabel = root.Find("CountLabel").GetComponent<UILabel>();
		DecLabel = root.Find("EmptyInfo/DecLabel").GetComponent<UILabel>();
		EquipmentTipLabel = root.Find("ProductsScrollView/EquipmentTipLabel").GetComponent<UILabel>();
	}
}
