//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for ItemUseView.
/// </summary>
public class ItemUseView : BaseView
{
	public UIButton CloseBtn;
	public UIButton OptBtn;
	public UILabel OptlblLabel;
	public UIPageGrid itemGrid;
	public GameObject LGroup;

	public void Setup (Transform root)
	{
		CloseBtn = root.Find("RGroup/CloseBtn").GetComponent<UIButton>();
		OptBtn = root.Find("RGroup/OptBtn").GetComponent<UIButton>();
		OptlblLabel = root.Find("RGroup/OptBtn/OptlblLabel").GetComponent<UILabel>();
		itemGrid = root.Find("RGroup/ItemPanel/itemGrid").GetComponent<UIPageGrid>();
		LGroup = root.Find("LGroup").gameObject;
	}
}
