//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for AddPointSlider.
/// </summary>
public class AddPointSlider : BaseView
{
	public UILabel titleLbl;
	public UISlider addPointSlider;
	public UISlider originSlider;
	public UILabel originLbl;
	public UILabel addPointLbl;
	public UIEventTrigger minusEventTrigger;
	public UIEventTrigger addEventTrigger;
	public UISlider realSlider;
	public UISprite minusBtnSprite;
	public UISprite addBtnSprite;
	public BoxCollider thumbCollider;

	public void Setup (Transform root)
	{
		titleLbl = root.Find("titleLbl").GetComponent<UILabel>();
		addPointSlider = root.Find("sliderBg/addPointSlider").GetComponent<UISlider>();
		originSlider = root.Find("sliderBg/originSlider").GetComponent<UISlider>();
		originLbl = root.Find("originLbl").GetComponent<UILabel>();
		addPointLbl = root.Find("addPointLbl").GetComponent<UILabel>();
		minusEventTrigger = root.Find("minusBtn").GetComponent<UIEventTrigger>();
		addEventTrigger = root.Find("addBtn").GetComponent<UIEventTrigger>();
		realSlider = root.Find("sliderBg/realSlider").GetComponent<UISlider>();
		minusBtnSprite = root.Find("minusBtn").GetComponent<UISprite>();
		addBtnSprite = root.Find("addBtn").GetComponent<UISprite>();
		thumbCollider = root.Find("sliderBg/thumb").GetComponent<BoxCollider>();
	}
}
