//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for PropertyItmeWidget.
/// </summary>
public class PropertyItmeWidget : BaseView
{
	public UILabel valLbl;
	public UIEventListener rightBtn;
	public UISprite contentBg;
	public UIButton titleBtn;
	public UILabel titleLbl;
	public UIEventListener leftBtn;

	public void Setup (Transform root)
	{
		valLbl = root.Find("bgSprite/valueBg/valLbl").GetComponent<UILabel>();
		rightBtn = root.Find("bgSprite/valueBg/rightBtn").GetComponent<UIEventListener>();
		contentBg = root.Find("bgSprite").GetComponent<UISprite>();
		titleBtn = root.Find("bgSprite/titleBg").GetComponent<UIButton>();
		titleLbl = root.Find("bgSprite/titleBg/titleLbl").GetComponent<UILabel>();
		leftBtn = root.Find("bgSprite/valueBg/leftBtn").GetComponent<UIEventListener>();
	}
}
