//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for VigourWinUI.
/// </summary>
public class VigourWinUI : BaseView
{
	public UIButton CloseBtn;
	public UISprite BarSprite;
	public UILabel VigourVuale;
	public UILabel WorkVigourLabel;
	public UILabel FactionSKillVigourLabel;
	public GameObject WorkBtnPos;
	public GameObject AssistSkillBtn;
	public GameObject FactionSKillBtn;
	public UILabel FactionSkillLabel;

	public void Setup (Transform root)
	{
		CloseBtn = root.Find("CloseBtn").GetComponent<UIButton>();
		BarSprite = root.Find("infoGroup/VigourGroup/Sprite/BarSprite").GetComponent<UISprite>();
		VigourVuale = root.Find("infoGroup/VigourGroup/VigourVuale").GetComponent<UILabel>();
		WorkVigourLabel = root.Find("infoGroup/WorkVigourLabel").GetComponent<UILabel>();
		FactionSKillVigourLabel = root.Find("infoGroup/FactionSKillVigourLabel").GetComponent<UILabel>();
		WorkBtnPos = root.Find("infoGroup/WorkBtnPos").gameObject;
		AssistSkillBtn = root.Find("infoGroup/AssistSkillBtn").gameObject;
		FactionSKillBtn = root.Find("infoGroup/FactionSKillBtn").gameObject;
		FactionSkillLabel = root.Find("infoGroup/FactionSkillLabel").GetComponent<UILabel>();
	}
}
