//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for PlayerAppellationView.
/// </summary>
public class PlayerAppellationView : BaseView
{
	public UIButton closeBtn;
	public UIGrid itemGrid;
	public GameObject appellationItemPrefab;
	public UILabel descLbl;
	public UIButton changBtn;
	public UIButton hideBtn;
	public UIScrollView descScrollView;

	public void Setup (Transform root)
	{
		closeBtn = root.Find("ContentBg/CloseBtn").GetComponent<UIButton>();
		itemGrid = root.Find("ContentBg/appellationItemBg/ScrollView/itemGrid").GetComponent<UIGrid>();
		appellationItemPrefab = root.Find("ContentBg/appellationItemBg/ScrollView/itemGrid/appellationItem").gameObject;
		descLbl = root.Find("ContentBg/descBg/ScrollView/descLbl").GetComponent<UILabel>();
		changBtn = root.Find("ContentBg/changBtn").GetComponent<UIButton>();
		hideBtn = root.Find("ContentBg/hideBtn").GetComponent<UIButton>();
		descScrollView = root.Find("ContentBg/descBg/ScrollView").GetComponent<UIScrollView>();
	}
}
