//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for AssistSkillLearningWinUI.
/// </summary>
public class AssistSkillLearningWinUI : BaseView
{
	public UIButton CloseBtn;
	public UIGrid TabGroup;

	public void Setup (Transform root)
	{
		CloseBtn = root.Find("CloseBtn").GetComponent<UIButton>();
		TabGroup = root.Find("TabGroup").GetComponent<UIGrid>();
	}
}
