//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for MarketView.
/// </summary>
public class MarketView : BaseView
{
	public UILabel PageLabel_UILabel;
	public UIButton RefreshButton_UIButton;
	public UIButton BuyButton_UIButton;
	public UIButton NextPageButton_UIButton;
	public UIButton PrePageButton_UIButton;
	public Transform BuyGroup_Transform;
	public UILabel MoneyLbl_UILabel;
	public UILabel TimeLabel_UILabel;
	public UIGrid TypeGrid_UIGrid;
	public PageScrollView ItemCellGrid_PageScrollView;
	public Transform SellGroup_Transform;
	public UIGrid SellGrid_UIGrid;
	public UIButton QuickAddButton_UIButton;
	public UIButton QuickGainButton_UIButton;
	public UIGrid TabGrid_UIGrid;
	public UIScrollView ScrollView_UIScrollView;
	public UILabel RefLabel_UILabel;
	public Transform ReGo_Transform;

	public void Setup (Transform root)
	{
		PageLabel_UILabel = root.Find("BuyGroup/PageLabel").GetComponent<UILabel>();
		RefreshButton_UIButton = root.Find("BuyGroup/RefreshButton").GetComponent<UIButton>();
		BuyButton_UIButton = root.Find("BuyGroup/BuyButton").GetComponent<UIButton>();
		NextPageButton_UIButton = root.Find("BuyGroup/NextPageButton").GetComponent<UIButton>();
		PrePageButton_UIButton = root.Find("BuyGroup/PrePageButton").GetComponent<UIButton>();
		BuyGroup_Transform = root.Find("BuyGroup");
		MoneyLbl_UILabel = root.Find("MoneyInfo/valueBg/valLbl").GetComponent<UILabel>();
		TimeLabel_UILabel = root.Find("BuyGroup/TimeLabel").GetComponent<UILabel>();
		TypeGrid_UIGrid = root.Find("BuyGroup/ListGroup/ScrollView/TypeGrid").GetComponent<UIGrid>();
		ItemCellGrid_PageScrollView = root.Find("BuyGroup/ItemGroup/ScrollView/ItemCellGrid").GetComponent<PageScrollView>();
		SellGroup_Transform = root.Find("SellGroup");
		SellGrid_UIGrid = root.Find("SellGroup/ScrollView/SellGrid").GetComponent<UIGrid>();
		QuickAddButton_UIButton = root.Find("SellGroup/QuickAddButton").GetComponent<UIButton>();
		QuickGainButton_UIButton = root.Find("SellGroup/QuickGainButton").GetComponent<UIButton>();
		TabGrid_UIGrid = root.Find("TabGrid").GetComponent<UIGrid>();
		ScrollView_UIScrollView = root.Find("BuyGroup/ListGroup/ScrollView").GetComponent<UIScrollView>();
		RefLabel_UILabel = root.Find("BuyGroup/RefreshButton/RefLabel").GetComponent<UILabel>();
		ReGo_Transform = root.Find("BuyGroup/RefreshButton/ReGo");
	}
}
