//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for TreasureMapView.
/// </summary>
public class TreasureMapView : BaseView
{
	public UIGrid ItemGrid;
	public UIButton OkBtn;
	public UIButton CloseBtn;

	public void Setup (Transform root)
	{
		ItemGrid = root.Find("Content/ItemGrid").GetComponent<UIGrid>();
		OkBtn = root.Find("Content/OkBtn").GetComponent<UIButton>();
		CloseBtn = root.Find("Content/CloseBtn").GetComponent<UIButton>();
	}
}
