//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for PetBaseInfoView.
/// </summary>
public class PetBaseInfoView : BaseView
{
	public Transform modelAnchor;
	public UIButton petTypeBtn;
	public UIButton petRankingBtn;
	public UILabel petRankingLbl;
	public UISlider expSlider;
	public UILabel expLbl;
	public UIButton petGrowthInfoBtn;
	public UIGrid petEqItemGrid;
	public UIGrid petInfoTabBtnGrid;
	public GameObject TabContent_BaseProperty;
	public GameObject TabContent_PetAptitude;
	public GameObject TabContent_PetSkill;
	public UIButton decorationBtn;
	public GameObject modelBtnGroup;

	public void Setup (Transform root)
	{
		modelAnchor = root.Find("ContentBg/TopInfoGroup/ModelAnchor");
		petTypeBtn = root.Find("ContentBg/TopInfoGroup/ModelAnchor/ButtonPanel/petTypeBtn").GetComponent<UIButton>();
		petRankingBtn = root.Find("ContentBg/TopInfoGroup/PetRankingInfo/titleBg").GetComponent<UIButton>();
		petRankingLbl = root.Find("ContentBg/TopInfoGroup/PetRankingInfo/valueBg/valLbl").GetComponent<UILabel>();
		expSlider = root.Find("ContentBg/TopInfoGroup/ExpInfo/slider").GetComponent<UISlider>();
		expLbl = root.Find("ContentBg/TopInfoGroup/ExpInfo/slider/valueLbl").GetComponent<UILabel>();
		petGrowthInfoBtn = root.Find("ContentBg/TopInfoGroup/PetGrowthInfoBtn").GetComponent<UIButton>();
		petEqItemGrid = root.Find("ContentBg/TopInfoGroup/EquipmentGroup").GetComponent<UIGrid>();
		petInfoTabBtnGrid = root.Find("ContentBg/BottomInfoGroup/TabBtnGrid").GetComponent<UIGrid>();
		TabContent_BaseProperty = root.Find("ContentBg/BottomInfoGroup/TabContentRoot/TabContent_BaseProperty").gameObject;
		TabContent_PetAptitude = root.Find("ContentBg/BottomInfoGroup/TabContentRoot/TabContent_PetAptitude").gameObject;
		TabContent_PetSkill = root.Find("ContentBg/BottomInfoGroup/TabContentRoot/TabContent_PetSkill").gameObject;
		decorationBtn = root.Find("ContentBg/TopInfoGroup/ModelAnchor/ButtonPanel/decorationBtn").GetComponent<UIButton>();
		modelBtnGroup = root.Find("ContentBg/TopInfoGroup/ModelAnchor/ButtonPanel").gameObject;
	}
}
