//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for PetEquipmentCombineView.
/// </summary>
public class PetEquipmentCombineView : BaseView
{
	public UIButton closeBtn;
	public UIGrid combineItemGrid;
	public GameObject resultItemAnchor;
	public PageScrollView eqItemPageGrid;
	public UIButton combineBtn;
	public UIButton combineHintBtn;

	public void Setup (Transform root)
	{
		closeBtn = root.Find("ContentBg/CloseBtn").GetComponent<UIButton>();
		combineItemGrid = root.Find("ContentBg/CombineItemGroup/combineItemGrid").GetComponent<UIGrid>();
		resultItemAnchor = root.Find("ContentBg/CombineItemGroup/resultItemAnchor").gameObject;
		eqItemPageGrid = root.Find("ContentBg/PetEquipmentItemGroup/petItemScrollView/itemGrid").GetComponent<PageScrollView>();
		combineBtn = root.Find("ContentBg/combineBtn").GetComponent<UIButton>();
		combineHintBtn = root.Find("ContentBg/combineBtn/hintBtn").GetComponent<UIButton>();
	}
}
