//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for PetHandBookView.
/// </summary>
public class PetHandBookView : BaseView
{
	public UIGrid petTypeTabBtnGrid;
	public PageScrollView petItemGrid;
	public Transform modelAnchor;
	public UILabel petNameLbl;
	public UIGrid petApItemGrid;
	public UIGrid skillItemGrid;
	public GameObject regularGroup;
	public GameObject mythGroup;
	public UIButton buyBtn;
	public UIButton captiveBtn;
	public UILabel captiveBtnLbl;
	public UIButton captiveHintBtn;
	public UIButton buyHintBtn;
	public UIButton exchangeBtn;
	public UIButton petTypeBtn;
	public UIGrid pageFlagGrid;
	public GameObject propItemAnchor;
	public UILabel achieveTipsLbl;

	public void Setup (Transform root)
	{
		petTypeTabBtnGrid = root.Find("petTypeTabBtnGrid").GetComponent<UIGrid>();
		petItemGrid = root.Find("petTypeTabContent/petItemScrollView/itemGrid").GetComponent<PageScrollView>();
		modelAnchor = root.Find("petDetailInfoGroup/ModelAnchor");
		petNameLbl = root.Find("petDetailInfoGroup/petNameLbl").GetComponent<UILabel>();
		petApItemGrid = root.Find("petDetailInfoGroup/petApItemGrid").GetComponent<UIGrid>();
		skillItemGrid = root.Find("petDetailInfoGroup/petSkillInfo/skillItemGrid").GetComponent<UIGrid>();
		regularGroup = root.Find("petDetailInfoGroup/petAchieveInfo/regularGroup").gameObject;
		mythGroup = root.Find("petDetailInfoGroup/petAchieveInfo/mythGroup").gameObject;
		buyBtn = root.Find("petDetailInfoGroup/petAchieveInfo/regularGroup/buyBtn").GetComponent<UIButton>();
		captiveBtn = root.Find("petDetailInfoGroup/petAchieveInfo/regularGroup/captiveBtn").GetComponent<UIButton>();
		captiveBtnLbl = root.Find("petDetailInfoGroup/petAchieveInfo/regularGroup/captiveBtn/btnLbl").GetComponent<UILabel>();
		captiveHintBtn = root.Find("petDetailInfoGroup/petAchieveInfo/regularGroup/captiveHintBtn").GetComponent<UIButton>();
		buyHintBtn = root.Find("petDetailInfoGroup/petAchieveInfo/regularGroup/buyHintBtn").GetComponent<UIButton>();
		exchangeBtn = root.Find("petDetailInfoGroup/petAchieveInfo/mythGroup/exchangeBtn").GetComponent<UIButton>();
		petTypeBtn = root.Find("petDetailInfoGroup/ModelAnchor/ButtonPanel/petTypeBtn").GetComponent<UIButton>();
		pageFlagGrid = root.Find("petTypeTabContent/pageFlagGrid").GetComponent<UIGrid>();
		propItemAnchor = root.Find("petDetailInfoGroup/petAchieveInfo/mythGroup/propItemAnchor").gameObject;
		achieveTipsLbl = root.Find("petDetailInfoGroup/petAchieveInfo/achieveTipsLbl").GetComponent<UILabel>();
	}
}
