//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for PetIncreaseBaseApView.
/// </summary>
public class PetIncreaseBaseApView : BaseView
{
	public UIGrid baseApItemGrid;
	public UIButton closeBtn;
	public UISprite petIconSprite;
	public UILabel petNameLbl;
	public UILabel petLvLbl;
	public UISprite propIconSprite;
	public UILabel propCountLbl;

	public void Setup (Transform root)
	{
		baseApItemGrid = root.Find("BgSprite/baseApItemGrid").GetComponent<UIGrid>();
		closeBtn = root.Find("BgSprite/CloseButton").GetComponent<UIButton>();
		petIconSprite = root.Find("BgSprite/ContentGroup/iconBg/iconSprite").GetComponent<UISprite>();
		petNameLbl = root.Find("BgSprite/ContentGroup/petNameLbl").GetComponent<UILabel>();
		petLvLbl = root.Find("BgSprite/ContentGroup/petLvLbl").GetComponent<UILabel>();
		propIconSprite = root.Find("BgSprite/ContentGroup/PropItemCell/iconBg/iconSprite").GetComponent<UISprite>();
		propCountLbl = root.Find("BgSprite/ContentGroup/PropItemCell/iconBg/Label").GetComponent<UILabel>();
	}
}
