//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for PropertySliderWidget.
/// </summary>
public class PropertySliderWidget : BaseView
{
	public UISlider slider;
	public UILabel titleLbl;
	public UILabel valueLbl;
	public UIButton titleBtn;
	public UISprite sliderBg;
	public UIButton valueBtn;
	public UISprite foreground;

	public void Setup (Transform root)
	{
		slider = root.Find("slider").GetComponent<UISlider>();
		titleLbl = root.Find("titleBg/titleLbl").GetComponent<UILabel>();
		valueLbl = root.Find("slider/valueLbl").GetComponent<UILabel>();
		titleBtn = root.Find("titleBg").GetComponent<UIButton>();
		sliderBg = root.Find("slider").GetComponent<UISprite>();
		valueBtn = root.Find("slider/valueBtn").GetComponent<UIButton>();
		foreground = root.Find("slider/foreground").GetComponent<UISprite>();
	}
}
