//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for BackpackItemCellInMarketSellView.
/// </summary>
public class BackpackItemCellInMarketSellView : BaseView
{
	public UILabel SellratioLabel_UILabel;
	public UISprite LockSprite_UISprite;

	public void Setup (Transform root)
	{
		SellratioLabel_UILabel = root.Find("SellratioLabel").GetComponent<UILabel>();
		LockSprite_UISprite = root.Find("LockSprite").GetComponent<UISprite>();
	}
}
