//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for SellItemCell.
/// </summary>
public class SellItemCell : BaseView
{
	public Transform LockGroup_Transform;
	public Transform AddGroup_Transform;
	public Transform SellGroup_Transform;
	public UISprite SelectSprite_UISprite;
	public UILabel CostLabel_UILabel;
	public UILabel NameLabel_UILabel;
	public UISprite StatusSprite_UISprite;
	public UILabel ItemCountLabel_UILabel;
	public UISprite ItemIcon_UISprite;
	public UIButton SellItemCell_UIButton;
	public UILabel MoneyLabel_UILabel;
	public UISprite SellItemCell_UISprite;
	public UIButton BgSprite_UIButton;

	public void Setup (Transform root)
	{
		LockGroup_Transform = root.Find("LockGroup");
		AddGroup_Transform = root.Find("AddGroup");
		SellGroup_Transform = root.Find("SellGroup");
		SelectSprite_UISprite = root.Find("SelectSprite").GetComponent<UISprite>();
		CostLabel_UILabel = root.Find("SellGroup/CostLabel").GetComponent<UILabel>();
		NameLabel_UILabel = root.Find("SellGroup/NameLabel").GetComponent<UILabel>();
		StatusSprite_UISprite = root.Find("SellGroup/ItemCell/StatusSprite").GetComponent<UISprite>();
		ItemCountLabel_UILabel = root.Find("SellGroup/ItemCell/ItemCountLabel").GetComponent<UILabel>();
		ItemIcon_UISprite = root.Find("SellGroup/ItemCell/ItemIcon").GetComponent<UISprite>();
	SellItemCell_UIButton = root.GetComponent<UIButton>();
		MoneyLabel_UILabel = root.Find("LockGroup/Sprite/MoneyLabel").GetComponent<UILabel>();
	SellItemCell_UISprite = root.GetComponent<UISprite>();
		BgSprite_UIButton = root.Find("BgSprite").GetComponent<UIButton>();
	}
}
