//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for AssistSkillRefineWinUI.
/// </summary>
public class AssistSkillRefineWinUI : BaseView
{
	public UIButton CloseBtn;
	public GameObject RefineGroup;
	public UILabel VigourValLbl;
	public UIGrid MaterialsGrid;
	public GameObject ProductsItemPos;
	public UIGrid ItemGrid;
	public UIButton OptBtn;
	public GameObject OptBtnPos;
	public UIButton TipsBtn;
	public GameObject PreviewGroup;
	public UIGrid PreviewGrid;
	public UIGrid TabGroup;

	public void Setup (Transform root)
	{
		CloseBtn = root.Find("CloseBtn").GetComponent<UIButton>();
		RefineGroup = root.Find("RefineGroup").gameObject;
		VigourValLbl = root.Find("RefineGroup/vigour/bgSprite/valueBg/VigourValLbl").GetComponent<UILabel>();
		MaterialsGrid = root.Find("RefineGroup/MaterialsGrid").GetComponent<UIGrid>();
		ProductsItemPos = root.Find("RefineGroup/ProductsItemPos").gameObject;
		ItemGrid = root.Find("RefineGroup/ItemGrid").GetComponent<UIGrid>();
		OptBtn = root.Find("RefineGroup/OptBtn").GetComponent<UIButton>();
		OptBtnPos = root.Find("RefineGroup/OptBtnPos").gameObject;
		TipsBtn = root.Find("RefineGroup/TipsBtn").GetComponent<UIButton>();
		PreviewGroup = root.Find("PreviewGroup").gameObject;
		PreviewGrid = root.Find("PreviewGroup/PreviewGrid").GetComponent<UIGrid>();
		TabGroup = root.Find("TabGroup").GetComponent<UIGrid>();
	}
}
