//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for EquipmentGemTransferView.
/// </summary>
public class EquipmentGemTransferView : BaseView
{
	public UILabel LTipsLabel;
	public UIButton LButton;
	public UIButton RButton;
	public UIGrid EquipmentGroup;
	public UILabel RuleTipsLabel;
	public UILabel RuleLabel;
	public GameObject CurrEquipInfoGroup;
	public GameObject CurrEquipPos;
	public UILabel EquipmentPropertyLabel;
	public UIGrid MaterialGrid;
	public UIButton OptButton;
	public GameObject TargetEquipPos;
	public UILabel TargetEquipmentPropertyLabel;
	public UILabel CostLabel;
	public UILabel OptNameLabel;

	public void Setup (Transform root)
	{
		LTipsLabel = root.Find("LeftGroup/pageGroup/Sprite/LTipsLabel").GetComponent<UILabel>();
		LButton = root.Find("LeftGroup/pageGroup/LButton").GetComponent<UIButton>();
		RButton = root.Find("LeftGroup/pageGroup/RButton").GetComponent<UIButton>();
		EquipmentGroup = root.Find("LeftGroup/EquipmentGroup").GetComponent<UIGrid>();
		RuleTipsLabel = root.Find("TopRightGroup/Sprite/RuleTipsLabel").GetComponent<UILabel>();
		RuleLabel = root.Find("TopRightGroup/RuleLabel").GetComponent<UILabel>();
		CurrEquipInfoGroup = root.Find("TopRightGroup/CurrEquipInfoGroup").gameObject;
		CurrEquipPos = root.Find("TopRightGroup/CurrEquipInfoGroup/CurrEquipPos").gameObject;
		EquipmentPropertyLabel = root.Find("TopRightGroup/CurrEquipInfoGroup/EquipmentPropertyScrollView/EquipmentPropertyLabel").GetComponent<UILabel>();
		MaterialGrid = root.Find("BottomRightGroup/MaterialGrid").GetComponent<UIGrid>();
		OptButton = root.Find("BottomRightGroup/OptButton").GetComponent<UIButton>();
		TargetEquipPos = root.Find("TopRightGroup/TargetEquipInfoGroup/TargetEquipPos").gameObject;
		TargetEquipmentPropertyLabel = root.Find("TopRightGroup/TargetEquipInfoGroup/EquipmentPropertyScrollView/TargetEquipmentPropertyLabel").GetComponent<UILabel>();
		CostLabel = root.Find("BottomRightGroup/OptButton/CostLabel").GetComponent<UILabel>();
		OptNameLabel = root.Find("BottomRightGroup/OptButton/OptNameLabel").GetComponent<UILabel>();
	}
}
