//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for EquipmentOptCell.
/// </summary>
public class EquipmentOptCell : BaseView
{
	public UIButton EquipmenOptCellBtn;
	public UISprite EquipIcon;
	public GameObject GemTopCell;
	public UISprite GemTopIcon;
	public GameObject GemBottomCell;
	public UISprite GemBottomIcon;
	public UILabel EquipNameLabel;
	public UILabel EquipPartLabel;
	public UISprite SelectSprite;
	public UISprite GemTransferSprite;

	public void Setup (Transform root)
	{
	EquipmenOptCellBtn = root.GetComponent<UIButton>();
		EquipIcon = root.Find("EquipCell/EquipIcon").GetComponent<UISprite>();
		GemTopCell = root.Find("GemTopCell").gameObject;
		GemTopIcon = root.Find("GemTopCell/GemTopIcon").GetComponent<UISprite>();
		GemBottomCell = root.Find("GemBottomCell").gameObject;
		GemBottomIcon = root.Find("GemBottomCell/GemBottomIcon").GetComponent<UISprite>();
		EquipNameLabel = root.Find("EquipNameLabel").GetComponent<UILabel>();
		EquipPartLabel = root.Find("EquipPartLabel").GetComponent<UILabel>();
	SelectSprite = root.GetComponent<UISprite>();
		GemTransferSprite = root.Find("GemTransferSprite").GetComponent<UISprite>();
	}
}
