//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for EquipmentPropertyView.
/// </summary>
public class EquipmentPropertyView : BaseView
{
	public UIButton LBtn;
	public UIButton RBtn;
	public UIGrid EquipmentGrid;
	public UIGrid PropertyGrid;
	public GameObject CurrEquipPos;
	public UILabel EquipmentPropertyLabel;
	public UIGrid MaterialGrid;
	public UILabel CostLabel;
	public UIButton OptButton;
	public UILabel OptNameLabel;

	public void Setup (Transform root)
	{
		LBtn = root.Find("LeftGroup/pageGroup/LButton").GetComponent<UIButton>();
		RBtn = root.Find("LeftGroup/pageGroup/RButton").GetComponent<UIButton>();
		EquipmentGrid = root.Find("LeftGroup/EquipmentGroup").GetComponent<UIGrid>();
		PropertyGrid = root.Find("TopRightGroup/PropertyGrid").GetComponent<UIGrid>();
		CurrEquipPos = root.Find("TopRightGroup/CurrEquipPos").gameObject;
		EquipmentPropertyLabel = root.Find("TopRightGroup/EquipmentPropertyScrollView/EquipmentPropertyLabel").GetComponent<UILabel>();
		MaterialGrid = root.Find("BottomRightGroup/MaterialGrid").GetComponent<UIGrid>();
		CostLabel = root.Find("BottomRightGroup/OptButton/CostLabel").GetComponent<UILabel>();
		OptButton = root.Find("BottomRightGroup/OptButton").GetComponent<UIButton>();
		OptNameLabel = root.Find("BottomRightGroup/OptButton/OptNameLabel").GetComponent<UILabel>();
	}
}
