//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for EquipmentManufacturingView.
/// </summary>
public class EquipmentManufacturingView : BaseView
{
	public UIButton LBtn;
	public UIButton RBtn;
	public UIGrid EquipmentGroupGrid;
	public GameObject ProductsPos;
	public GameObject IdentificationPos;
	public GameObject CurrEquipPos;
	public GameObject IdentificationBtnPos;
	public UILabel EquipmentPropertyLabel;
	public UIGrid MaterialGrid;
	public UIToggle QuickToggle;
	public UIButton OptButton;
	public UILabel CostLabel;
	public UIButton QuickToggleBtn;
	public GameObject IdentifyGroup;
	public UILabel ProductsPropertyLabel;
	public UILabel OptNameLabel;
	public UISprite newSprite;

	public void Setup (Transform root)
	{
		LBtn = root.Find("LeftGroup/pageGroup/LButton").GetComponent<UIButton>();
		RBtn = root.Find("LeftGroup/pageGroup/RButton").GetComponent<UIButton>();
		EquipmentGroupGrid = root.Find("LeftGroup/EquipmentGroup").GetComponent<UIGrid>();
		ProductsPos = root.Find("TopRightGroup/ProductsPos").gameObject;
		IdentificationPos = root.Find("TopRightGroup/IdentifyGroup/IdentificationPos").gameObject;
		CurrEquipPos = root.Find("TopRightGroup/CurrEquipPos").gameObject;
		IdentificationBtnPos = root.Find("TopRightGroup/IdentifyGroup/IdentificationBtnPos").gameObject;
		EquipmentPropertyLabel = root.Find("TopRightGroup/EquipmentPropertyScrollView/EquipmentPropertyLabel").GetComponent<UILabel>();
		MaterialGrid = root.Find("BottomRightGroup/MaterialGrid").GetComponent<UIGrid>();
		QuickToggle = root.Find("BottomRightGroup/Toggle").GetComponent<UIToggle>();
		OptButton = root.Find("BottomRightGroup/OptButton").GetComponent<UIButton>();
		CostLabel = root.Find("BottomRightGroup/OptButton/CostLabel").GetComponent<UILabel>();
		QuickToggleBtn = root.Find("BottomRightGroup/Toggle").GetComponent<UIButton>();
		IdentifyGroup = root.Find("TopRightGroup/IdentifyGroup").gameObject;
		ProductsPropertyLabel = root.Find("TopRightGroup/ProductsScrollView/ProductsPropertyLabel").GetComponent<UILabel>();
		OptNameLabel = root.Find("BottomRightGroup/OptButton/OptNameLabel").GetComponent<UILabel>();
		newSprite = root.Find("TopRightGroup/newSprite").GetComponent<UISprite>();
	}
}
