//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for AssistSkillCookWinUI.
/// </summary>
public class AssistSkillCookWinUI : BaseView
{
	public UIButton CloseBtn;
	public UIGrid ItemGrid;
	public UILabel VigourValLbl;
	public UILabel UsageDescLabel;
	public GameObject OptBtnPos;

	public void Setup (Transform root)
	{
		CloseBtn = root.Find("CloseBtn").GetComponent<UIButton>();
		ItemGrid = root.Find("ItemGrid").GetComponent<UIGrid>();
		VigourValLbl = root.Find("vigour/bgSprite/valueBg/VigourValLbl").GetComponent<UILabel>();
		UsageDescLabel = root.Find("UsageDescLabel").GetComponent<UILabel>();
		OptBtnPos = root.Find("OptBtnPos").gameObject;
	}
}
