//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for ApplicationItemWidget.
/// </summary>
public class ApplicationItemWidget : BaseView
{
	public UILabel nameLbl;
	public UILabel factionInfoLbl;
	public UIButton applyBtn;

	public void Setup (Transform root)
	{
		nameLbl = root.Find("nameLbl").GetComponent<UILabel>();
		factionInfoLbl = root.Find("factionInfoLbl").GetComponent<UILabel>();
		applyBtn = root.Find("applyBtn").GetComponent<UIButton>();
	}
}
