//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for GemItemCell.
/// </summary>
public class GemItemCell : BaseView
{
	public UIButton RomeveBtn;

	public void Setup (Transform root)
	{
		RomeveBtn = root.Find("RomeveBtn").GetComponent<UIButton>();
	}
}
