//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for ItemRetrieveWinUI.
/// </summary>
public class ItemRetrieveWinUI : BaseView
{
	public UIButton CloseBtn;
	public GameObject OptBtnPos;
	public UIGrid ItemsGrid;

	public void Setup (Transform root)
	{
		CloseBtn = root.Find("BgGroup/CloseBtn").GetComponent<UIButton>();
		OptBtnPos = root.Find("OptBtnPos").gameObject;
		ItemsGrid = root.Find("ItemsGroup/ItemsGrid").GetComponent<UIGrid>();
	}
}
