//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for PetWarehouseWinUI.
/// </summary>
public class PetWarehouseWinUI : BaseView
{
	public UIButton CloseBtn;

	public void Setup (Transform root)
	{
		CloseBtn = root.Find("bgGroup/CloseBtn").GetComponent<UIButton>();
	}
}
