//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for ExpandContentTeamItem.
/// </summary>
public class ExpandContentTeamItem : BaseView
{
	public UISprite iconSprite;
	public UILabel infoLbl;
	public UILabel statusLbl;
	public UISprite factionIcon;
	public UISlider hpSlider;
	public UISlider mpSlider;
	public UIButton bgBtn;

	public void Setup (Transform root)
	{
		iconSprite = root.Find("IconBg/Icon").GetComponent<UISprite>();
		infoLbl = root.Find("InfoLbl").GetComponent<UILabel>();
		statusLbl = root.Find("IconBg/Icon/statusLbl").GetComponent<UILabel>();
		factionIcon = root.Find("factionIcon").GetComponent<UISprite>();
		hpSlider = root.Find("sliderGroup/hpSlider").GetComponent<UISlider>();
		mpSlider = root.Find("sliderGroup/mpSlider").GetComponent<UISlider>();
	bgBtn = root.GetComponent<UIButton>();
	}
}
