//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for ChatItemCellView.
/// </summary>
public class ChatItemCellView : BaseView
{
	public UIAnchor FaceBgAnchor;
	public UISprite FaceIcon;
	public UIAnchor ContentLblAnchor;
	public UILabel ContentLbl;
	public UISprite ContentBg;
	public UILabel PlayerNameLbl;
	public UISprite FaceBg;
	public UILabel JobLbl;
	public UIWidget widget;
	public UIButton PlayBtn;
	public UIButton FaceIconBtn;
	public UILabel LvLbl;

	public void Setup (Transform root)
	{
		FaceBgAnchor = root.Find("FaceBg").GetComponent<UIAnchor>();
		FaceIcon = root.Find("FaceBg/FaceIcon").GetComponent<UISprite>();
		ContentLblAnchor = root.Find("ContentLbl").GetComponent<UIAnchor>();
		ContentLbl = root.Find("ContentLbl").GetComponent<UILabel>();
		ContentBg = root.Find("ContentBg").GetComponent<UISprite>();
		PlayerNameLbl = root.Find("PlayerName").GetComponent<UILabel>();
		FaceBg = root.Find("FaceBg").GetComponent<UISprite>();
		JobLbl = root.Find("job").GetComponent<UILabel>();
	widget = root.GetComponent<UIWidget>();
		PlayBtn = root.Find("ContentBg").GetComponent<UIButton>();
		FaceIconBtn = root.Find("FaceBg").GetComponent<UIButton>();
		LvLbl = root.Find("FaceBg/LvLbl").GetComponent<UILabel>();
	}
}
