//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for FacePanelView.
/// </summary>
public class FacePanelView : BaseView
{
	public UIButton ExpressionBtn;
	public UIButton AppellationBtn;
	public UIButton AchievementBtn;
	public UIButton AssignmentBtn;
	public UIButton PetBtn;
	public UIButton SkillBtn;
	public UIButton PartnerBtn;
	public UIButton GoodsBtn;
	public UIEventTrigger BgBoxCollider;
	public UIPageGrid GoodsGrid;
	public GameObject GoodsPageFlag;
	public UIScrollView ItemScrollView;
	public GameObject Tips;

	public void Setup (Transform root)
	{
		ExpressionBtn = root.Find("ContentFrame/LPanel/ExpressionBtn").GetComponent<UIButton>();
		AppellationBtn = root.Find("ContentFrame/LPanel/AppellationBtn").GetComponent<UIButton>();
		AchievementBtn = root.Find("ContentFrame/LPanel/AchievementBtn").GetComponent<UIButton>();
		AssignmentBtn = root.Find("ContentFrame/LPanel/AssignmentBtn").GetComponent<UIButton>();
		PetBtn = root.Find("ContentFrame/LPanel/PetBtn").GetComponent<UIButton>();
		SkillBtn = root.Find("ContentFrame/LPanel/SkillBtn").GetComponent<UIButton>();
		PartnerBtn = root.Find("ContentFrame/LPanel/PartnerBtn").GetComponent<UIButton>();
		GoodsBtn = root.Find("ContentFrame/LPanel/GoodsBtn").GetComponent<UIButton>();
		BgBoxCollider = root.Find("BoxCollider").GetComponent<UIEventTrigger>();
		GoodsGrid = root.Find("ContentFrame/RPanel/ItemScrollView/GoodsGrid").GetComponent<UIPageGrid>();
		GoodsPageFlag = root.Find("ContentFrame/RPanel/GoodsPageFlagGrid").gameObject;
		ItemScrollView = root.Find("ContentFrame/RPanel/ItemScrollView").GetComponent<UIScrollView>();
		Tips = root.Find("ContentFrame/Tips").gameObject;
	}
}
