//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for FriendPartnerItemCell.
/// </summary>
public class FriendPartnerItemCell : BaseView
{
	public UIButton FriendPartnerItemCellBtn;
	public UISprite IconSprite;
	public UISprite WarSprite;
	public UILabel NameLbl;
	public UILabel LvLbl;
	public UISprite Bg;

	public void Setup (Transform root)
	{
	FriendPartnerItemCellBtn = root.GetComponent<UIButton>();
		IconSprite = root.Find("Face/IconSprite").GetComponent<UISprite>();
		WarSprite = root.Find("Face/WarSprite").GetComponent<UISprite>();
		NameLbl = root.Find("NameLbl").GetComponent<UILabel>();
		LvLbl = root.Find("LvLbl").GetComponent<UILabel>();
		Bg = root.Find("Bg").GetComponent<UISprite>();
	}
}
