//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for BackpackWinUI.
/// </summary>
public class BackpackWinUI : BaseView
{
	public UIGrid LEquipGrid;
	public UIGrid REquipGrid;
	public GameObject ModelAnchor;
	public GameObject DefInfoPos;
	public GameObject SpeedInfoPos;
	public GameObject MagicInfoPos;
	public GameObject AttackInfoPos;
	public GameObject MpInfoPos;
	public GameObject HpInfoPos;
	public GameObject ArrangeBtnPos;
	public UIButton AddSilverBtn;
	public UILabel SilverValLbl;
	public UILabel SilverLbl;
	public UIButton AddCopperBtn;
	public UILabel CopperValLbl;
	public UILabel CopperLbl;
	public GameObject ItemsPos;
	public UIButton CloseBtn;

	public void Setup (Transform root)
	{
		LEquipGrid = root.Find("LeftGroup/CharactorGroup/LEquip").GetComponent<UIGrid>();
		REquipGrid = root.Find("LeftGroup/CharactorGroup/REquip").GetComponent<UIGrid>();
		ModelAnchor = root.Find("LeftGroup/ModelAnchor").gameObject;
		DefInfoPos = root.Find("LeftGroup/PropertyGroup/5_DefInfo").gameObject;
		SpeedInfoPos = root.Find("LeftGroup/PropertyGroup/6_SpeedInfo").gameObject;
		MagicInfoPos = root.Find("LeftGroup/PropertyGroup/4_MagicInfo").gameObject;
		AttackInfoPos = root.Find("LeftGroup/PropertyGroup/3_AttackInfo").gameObject;
		MpInfoPos = root.Find("LeftGroup/PropertyGroup/2_MpInfo").gameObject;
		HpInfoPos = root.Find("LeftGroup/PropertyGroup/1_HpInfo").gameObject;
		ArrangeBtnPos = root.Find("RightGroup/WealthGroup/ArrangeBtnPos").gameObject;
		AddSilverBtn = root.Find("RightGroup/WealthGroup/2_silver/bgSprite/valueBg/AddSilverBtn").GetComponent<UIButton>();
		SilverValLbl = root.Find("RightGroup/WealthGroup/2_silver/bgSprite/valueBg/valLbl").GetComponent<UILabel>();
		SilverLbl = root.Find("RightGroup/WealthGroup/2_silver/bgSprite/titleBg/titleLbl").GetComponent<UILabel>();
		AddCopperBtn = root.Find("RightGroup/WealthGroup/1_copper/bgSprite/valueBg/AddCopperBtn").GetComponent<UIButton>();
		CopperValLbl = root.Find("RightGroup/WealthGroup/1_copper/bgSprite/valueBg/valLbl").GetComponent<UILabel>();
		CopperLbl = root.Find("RightGroup/WealthGroup/1_copper/bgSprite/titleBg/titleLbl").GetComponent<UILabel>();
		ItemsPos = root.Find("RightGroup/ItemsPos").gameObject;
		CloseBtn = root.Find("bgGroup/CloseBtn").GetComponent<UIButton>();
	}
}
