//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for LoginView.
/// </summary>
public class LoginView : BaseView
{
	public UILabel VersionLabel_UILabel;
	public Transform StartPanel_Transform;
	public Transform LoadingPanel_Transform;
	public UITexture LoadingTexture_UITexture;
	public UIButton StartGameButton_UIButton;
	public UIButton LastLoginInfo_UIButton;
	public UILabel LastLoginInfo_label_UILabel;
	public UISprite LastLoginInfo_state_UISprite;
	public UILabel ErrorMsgLbl_UILabel;
	public UIInput NameInput_UIInput;
	public UILabel LoadingLabel_UILabel;
	public UILabel LoadingTips_UILabel;
	public UISlider LoadingProgressBar_UISlider;

	public void Setup (Transform root)
	{
		VersionLabel_UILabel = root.Find("TopRightAnchor/VersionLabel").GetComponent<UILabel>();
		StartPanel_Transform = root.Find("Content/StartPanel");
		LoadingPanel_Transform = root.Find("Content/LoadingPanel");
		LoadingTexture_UITexture = root.Find("Content/LoadingTexture").GetComponent<UITexture>();
		StartGameButton_UIButton = root.Find("Content/StartPanel/StartGameButton").GetComponent<UIButton>();
		LastLoginInfo_UIButton = root.Find("Content/StartPanel/LastLoginInfo").GetComponent<UIButton>();
		LastLoginInfo_label_UILabel = root.Find("Content/StartPanel/LastLoginInfo/LastLoginInfo_label").GetComponent<UILabel>();
		LastLoginInfo_state_UISprite = root.Find("Content/StartPanel/LastLoginInfo/LastLoginInfo_state").GetComponent<UISprite>();
		ErrorMsgLbl_UILabel = root.Find("Content/StartPanel/GmAccountInputGroup/ErrorMsgLbl").GetComponent<UILabel>();
		NameInput_UIInput = root.Find("Content/StartPanel/GmAccountInputGroup/NameInput").GetComponent<UIInput>();
		LoadingLabel_UILabel = root.Find("Content/LoadingPanel/LoadingLabel").GetComponent<UILabel>();
		LoadingTips_UILabel = root.Find("Content/LoadingPanel/LoadingTips").GetComponent<UILabel>();
		LoadingProgressBar_UISlider = root.Find("Content/LoadingPanel/LoadingProgressBar").GetComponent<UISlider>();
	}
}
