//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for HyperlinkMission.
/// </summary>
public class HyperlinkMission : BaseView
{
	public GameObject MIssionContentObj;
	public UILabel MissionDescription;
	public UILabel MissionTarget;
	public UILabel MissionName;
	public GameObject TitleContentObj;
	public UILabel TitleName;
	public UILabel TitleDescription;
	public GameObject SkillContentObj;
	public UILabel SkillName;
	public UILabel SkillDescription;
	public UIButton CloseBtn;

	public void Setup (Transform root)
	{
		MIssionContentObj = root.Find("Content/MIssionContent").gameObject;
		MissionDescription = root.Find("Content/MIssionContent/MissionDescription/Description").GetComponent<UILabel>();
		MissionTarget = root.Find("Content/MIssionContent/MissionTarget/Target").GetComponent<UILabel>();
		MissionName = root.Find("Content/MIssionContent/MissionName/Name").GetComponent<UILabel>();
		TitleContentObj = root.Find("Content/TitleContent").gameObject;
		TitleName = root.Find("Content/TitleContent/TitleName").GetComponent<UILabel>();
		TitleDescription = root.Find("Content/TitleContent/TitleName/TitleDescription").GetComponent<UILabel>();
		SkillContentObj = root.Find("Content/SkillContent").gameObject;
		SkillName = root.Find("Content/SkillContent/SkillName").GetComponent<UILabel>();
		SkillDescription = root.Find("Content/SkillContent/SkillName/SkillDescription").GetComponent<UILabel>();
		CloseBtn = root.Find("Content/CloseBtn").GetComponent<UIButton>();
	}
}
