//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for AuctionItemCellView.
/// </summary>
public class AuctionItemCellView : BaseView
{
	public UISprite AuctionSprite_UISprite;
	public UILabel CurrentPriceLabel_UILabel;
	public UILabel ItemCountLabel_UILabel;
	public UISprite ItemIcon_UISprite;
	public UILabel NameLabel_UILabel;
	public UILabel OnePriceLabel_UILabel;
	public UISprite SelectSprite_UISprite;
	public UILabel TimeleftLabel_UILabel;
	public UISprite BottomSprite_UISprite;
	public UISprite TopSprite_UISprite;
	public BoxCollider AuctionItemCellView_BoxCollider;
	public UILabel StateLabel_UILabel;
	public UIButton CancleAuctionBtn_UIButton;

	public void Setup (Transform root)
	{
		AuctionSprite_UISprite = root.Find("AuctionSprite").GetComponent<UISprite>();
		CurrentPriceLabel_UILabel = root.Find("CurrentPriceLabel").GetComponent<UILabel>();
		ItemCountLabel_UILabel = root.Find("ItemCell/ItemCountLabel").GetComponent<UILabel>();
		ItemIcon_UISprite = root.Find("ItemCell/ItemIcon").GetComponent<UISprite>();
		NameLabel_UILabel = root.Find("NameLabel").GetComponent<UILabel>();
		OnePriceLabel_UILabel = root.Find("OnePriceLabel").GetComponent<UILabel>();
		SelectSprite_UISprite = root.Find("SelectSprite").GetComponent<UISprite>();
		TimeleftLabel_UILabel = root.Find("TimeleftLabel").GetComponent<UILabel>();
		BottomSprite_UISprite = root.Find("StaicSprite/BottomSprite").GetComponent<UISprite>();
		TopSprite_UISprite = root.Find("StaicSprite/TopSprite").GetComponent<UISprite>();
	AuctionItemCellView_BoxCollider = root.GetComponent<BoxCollider>();
		StateLabel_UILabel = root.Find("StateLabel").GetComponent<UILabel>();
		CancleAuctionBtn_UIButton = root.Find("CancleAuctionBtn").GetComponent<UIButton>();
	}
}
