//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for BatchSellToMarketView.
/// </summary>
public class BatchSellToMarketView : BaseView
{
	public UIButton CloseButton_UIButton;
	public UIButton QuickAddButton_UIButton;
	public UILabel ItemCountLabel_UILabel;
	public UISprite ItemIconSprite_UISprite;
	public UILabel ItemNameLabel_UILabel;
	public UILabel PriceValLbl_UILabel;
	public UILabel CountValLbl_UILabel;
	public UILabel TotalPriceValLbl_UILabel;
	public UILabel FeeValLbl_UILabel;
	public Transform LeftGroup_Transform;
	public UILabel LeftCountLabel_UILabel;
	public UIButton CutbackButton_UIButton;
	public UIButton IncreaseButton_UIButton;
	public UIButton CutbackCountButton_UIButton;
	public UIButton IncreaseCountButton_UIButton;
	public UILabel IncrementLabel_UILabel;

	public void Setup (Transform root)
	{
		CloseButton_UIButton = root.Find("CloseButton").GetComponent<UIButton>();
		QuickAddButton_UIButton = root.Find("QuickAddButton").GetComponent<UIButton>();
		ItemCountLabel_UILabel = root.Find("RightGroup/ItemCell/CountLabel").GetComponent<UILabel>();
		ItemIconSprite_UISprite = root.Find("RightGroup/ItemCell/IconSprite").GetComponent<UISprite>();
		ItemNameLabel_UILabel = root.Find("RightGroup/ItemCell/NameLabel").GetComponent<UILabel>();
		PriceValLbl_UILabel = root.Find("RightGroup/PriceCellWidget/valueBg/valLbl").GetComponent<UILabel>();
		CountValLbl_UILabel = root.Find("RightGroup/CountCellWidget/valueBg/valLbl").GetComponent<UILabel>();
		TotalPriceValLbl_UILabel = root.Find("RightGroup/TotalPriceCellWidget/valueBg/valLbl").GetComponent<UILabel>();
		FeeValLbl_UILabel = root.Find("RightGroup/FeeCellWidget/valueBg/valLbl").GetComponent<UILabel>();
		LeftGroup_Transform = root.Find("LeftGroup");
		LeftCountLabel_UILabel = root.Find("LeftCountLabel").GetComponent<UILabel>();
		CutbackButton_UIButton = root.Find("RightGroup/PriceCellWidget/ModifiedBtn/CutbackButton").GetComponent<UIButton>();
		IncreaseButton_UIButton = root.Find("RightGroup/PriceCellWidget/ModifiedBtn/IncreaseButton").GetComponent<UIButton>();
		CutbackCountButton_UIButton = root.Find("RightGroup/PriceCellWidget/ModifiedBtn/CutbackCountButton").GetComponent<UIButton>();
		IncreaseCountButton_UIButton = root.Find("RightGroup/PriceCellWidget/ModifiedBtn/IncreaseCountButton").GetComponent<UIButton>();
		IncrementLabel_UILabel = root.Find("RightGroup/IncrementLabel").GetComponent<UILabel>();
	}
}
