//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for Comprehensive.
/// </summary>
public class ChannlView : BaseView
{
	public UISprite Background;
	public UILabel Lbl;

	public void Setup (Transform root)
	{
		Background = root.Find("Background").GetComponent<UISprite>();
		Lbl = root.Find("Label").GetComponent<UILabel>();
	}
}
