//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for MainUIBuffTipsView.
/// </summary>
public class MainUIBuffTipsView : BaseView
{
	public UITable itemTable;
	public GameObject buffTipsItemPrefab;
	public UIEventTrigger BgEventTrigger;

	public void Setup (Transform root)
	{
		itemTable = root.Find("ContentBg/ScrollView/itemTable").GetComponent<UITable>();
		buffTipsItemPrefab = root.Find("ContentBg/ScrollView/itemTable/buffTipsItem").gameObject;
		BgEventTrigger = root.Find("BgCollider").GetComponent<UIEventTrigger>();
	}
}
