//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for PetResumeCell.
/// </summary>
public class PetResumeCell : BaseView
{
	public UIEventTrigger PetResumeEventTrigger;
	public UILabel LvLbl;
	public UILabel NameLbl;
	public UISprite SelectSprite;

	public void Setup (Transform root)
	{
	PetResumeEventTrigger = root.GetComponent<UIEventTrigger>();
		LvLbl = root.Find("LvLbl").GetComponent<UILabel>();
		NameLbl = root.Find("NameLbl").GetComponent<UILabel>();
		SelectSprite = root.Find("SelectSprite").GetComponent<UISprite>();
	}
}
