//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for ScreenMask.
/// </summary>
public class ScreenMask : BaseView
{
	public UISprite MaskSprite;

	public void Setup (Transform root)
	{
		MaskSprite = root.Find("bg").GetComponent<UISprite>();
	}
}
