//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for ItemContainer.
/// </summary>
public class ItemContainer : BaseView
{
	public UIGrid ItemGrid;
	public UIPageInfo PageInfo;

	public void Setup (Transform root)
	{
		ItemGrid = root.Find("GridGroup").GetComponent<UIGrid>();
	PageInfo = root.GetComponent<UIPageInfo>();
	}
}
