//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for ItemCellEx.
/// </summary>
public class ItemCellEx : BaseView
{
	public UILabel NameLabel;
	public UILabel CountLabel;
	public UIButton TakeOffBtn;

	public void Setup (Transform root)
	{
		NameLabel = root.Find("NameLabel").GetComponent<UILabel>();
		CountLabel = root.Find("CountLabel").GetComponent<UILabel>();
		TakeOffBtn = root.Find("TakeOffBtn").GetComponent<UIButton>();
	}
}
