//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for AssistProductCell.
/// </summary>
public class AssistProductCell : BaseView
{
	public UILabel LvLabel;

	public void Setup (Transform root)
	{
		LvLabel = root.Find("LvLabel").GetComponent<UILabel>();
	}
}
