//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for PlayerInfoView.
/// </summary>
public class PlayerInfoView : BaseView
{
	public UIPanel uiPanel;
	public UISprite Bg;
	public UILabel PlayerNameLbl;
	public UILabel OnLine;
	public UILabel Level;
	public UILabel Sex;
	public UISprite FactionSprite;
	public UILabel IdLbl;
	public UILabel AppellationLbl;
	public UILabel FactionLbl;
	public UILabel PositionLbl;
	public UIGrid ButtonGrid;
	public UIButton AddFriendBtn;
	public UIButton BeginChatBtn;
	public UIButton InviteTeamBtn;
	public UIButton GiveBtn;
	public UIButton PKBtn;
	public UIButton VisitHomeBtn;
	public UILabel InviteTeamLbl;
	public UISprite VipSprite;
	public UILabel AddFriendLbl;
	public UISprite TeamSprite;
	public UILabel TeamNOLbl;

	public void Setup (Transform root)
	{
	uiPanel = root.GetComponent<UIPanel>();
		Bg = root.Find("Content").GetComponent<UISprite>();
		PlayerNameLbl = root.Find("Content/Info/PlayerNameLbl").GetComponent<UILabel>();
		OnLine = root.Find("Content/Info/OnLine").GetComponent<UILabel>();
		Level = root.Find("Content/Info/Level").GetComponent<UILabel>();
		Sex = root.Find("Content/Info/Sex").GetComponent<UILabel>();
		FactionSprite = root.Find("Content/Info/Faction").GetComponent<UISprite>();
		IdLbl = root.Find("Content/Info/ID/IdLbl").GetComponent<UILabel>();
		AppellationLbl = root.Find("Content/Info/Appellation/AppellationLbl").GetComponent<UILabel>();
		FactionLbl = root.Find("Content/Info/Faction/FactionLbl").GetComponent<UILabel>();
		PositionLbl = root.Find("Content/Info/Position/PositionLbl").GetComponent<UILabel>();
		ButtonGrid = root.Find("Content/ButtonGrid").GetComponent<UIGrid>();
		AddFriendBtn = root.Find("Content/ButtonGrid/AddFriendBtn").GetComponent<UIButton>();
		BeginChatBtn = root.Find("Content/ButtonGrid/BeginChatBtn").GetComponent<UIButton>();
		InviteTeamBtn = root.Find("Content/ButtonGrid/InviteTeamBtn").GetComponent<UIButton>();
		GiveBtn = root.Find("Content/ButtonGrid/GiveBtn").GetComponent<UIButton>();
		PKBtn = root.Find("Content/ButtonGrid/PKBtn").GetComponent<UIButton>();
		VisitHomeBtn = root.Find("Content/ButtonGrid/VisitHomeBtn").GetComponent<UIButton>();
		InviteTeamLbl = root.Find("Content/ButtonGrid/InviteTeamBtn/Label").GetComponent<UILabel>();
		VipSprite = root.Find("Content/Info/ID/VipSprite").GetComponent<UISprite>();
		AddFriendLbl = root.Find("Content/ButtonGrid/AddFriendBtn/Label").GetComponent<UILabel>();
		TeamSprite = root.Find("Content/Info/TeamSprite").GetComponent<UISprite>();
		TeamNOLbl = root.Find("Content/Info/TeamSprite/TeamNO").GetComponent<UILabel>();
	}
}
