//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for ShopItemCell.
/// </summary>
public class ShopItemCell : BaseView
{
	public UIButton ShopItemBtn;
	public UISprite ItemIcon;
	public UILabel NameLabel;
	public UILabel CostLabel;
	public UISprite SelectSprite;
	public UILabel ItemCountLabel;
	public UISprite CostIconSprite;

	public void Setup (Transform root)
	{
	ShopItemBtn = root.GetComponent<UIButton>();
		ItemIcon = root.Find("ItemCell/ItemIcon").GetComponent<UISprite>();
		NameLabel = root.Find("NameLabel").GetComponent<UILabel>();
		CostLabel = root.Find("CostLabel").GetComponent<UILabel>();
	SelectSprite = root.GetComponent<UISprite>();
		ItemCountLabel = root.Find("ItemCell/ItemCountLabel").GetComponent<UILabel>();
		CostIconSprite = root.Find("CostIconSprite").GetComponent<UISprite>();
	}
}
