//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for NumericInputWinUI.
/// </summary>
public class NumericInputWinUI : BaseView
{
	public UIButton CloseBtn;
	public UIButton Btn_0;
	public UIButton Btn_1;
	public UIButton Btn_2;
	public UIButton Btn_3;
	public UIButton Btn_4;
	public UIButton Btn_5;
	public UIButton Btn_6;
	public UIButton Btn_7;
	public UIButton Btn_8;
	public UIButton Btn_9;
	public UIButton Btn_backspace;
	public UIButton Btn_enter;
	public UIAnchor ViewAnchor;
	public UIButton BgBoxCollider;

	public void Setup (Transform root)
	{
		CloseBtn = root.Find("bgGroup/CloseBtn").GetComponent<UIButton>();
		Btn_0 = root.Find("BtnGrid/11_Button").GetComponent<UIButton>();
		Btn_1 = root.Find("BtnGrid/1_Button").GetComponent<UIButton>();
		Btn_2 = root.Find("BtnGrid/2_Button").GetComponent<UIButton>();
		Btn_3 = root.Find("BtnGrid/3_Button").GetComponent<UIButton>();
		Btn_4 = root.Find("BtnGrid/4_Button").GetComponent<UIButton>();
		Btn_5 = root.Find("BtnGrid/5_Button").GetComponent<UIButton>();
		Btn_6 = root.Find("BtnGrid/6_Button").GetComponent<UIButton>();
		Btn_7 = root.Find("BtnGrid/7_Button").GetComponent<UIButton>();
		Btn_8 = root.Find("BtnGrid/8_Button").GetComponent<UIButton>();
		Btn_9 = root.Find("BtnGrid/9_Button").GetComponent<UIButton>();
		Btn_backspace = root.Find("BtnGrid/10_Button").GetComponent<UIButton>();
		Btn_enter = root.Find("BtnGrid/12_Button").GetComponent<UIButton>();
	ViewAnchor = root.GetComponent<UIAnchor>();
		BgBoxCollider = root.Find("bgGroup/BgBoxCollider").GetComponent<UIButton>();
	}
}
