//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for ExpressionView.
/// </summary>
public class ExpressionView : BaseView
{
	public UISprite ExpressionBg;
	public UIButton ExpressionBtn;

	public void Setup (Transform root)
	{
	ExpressionBg = root.GetComponent<UISprite>();
	ExpressionBtn = root.GetComponent<UIButton>();
	}
}
