// **********************************************************************
// Copyright (c) 2013 Baoyugame. All rights reserved.
// File     :  KDTSServerInfo.cs
// Author   : wenlin
// Created  : 2014/7/2 
// Purpose  : 
// **********************************************************************
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class KDTSServerInfo
{
	//目标服务器ID
	public int targetServiceId;

	//服务器端口
	public int port;

	//游戏服编号
	public int serviceId;

	//是否需要PayUrl
	public bool needPayUrl;

	//HA 接入ID
	public int accessId;

	//服务器名称
	public string name;	
	
	//服务器状态 0：流畅  1：火爆 2: 繁忙
	public int runState;
	
	//服务器维护状态 0：关闭   1:开放   2:维护中
	public int dboState = 1;
	
	//是否推荐  0不是新服 1新服
	public int recommend;
	
	//版本限制
	public int limitVer = 0;
	
	//版本最大限制
	public int limitMaxVer = 0;	

	public KDTSServerInfo ()
	{
	}
}

