//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for AssistSkillLearningView.
/// </summary>
public class AssistSkillLearningView : BaseView
{
	public UIGrid AssistSkillCellGrid;
	public UILabel AssistSkillInfoTitleLabel;
	public UILabel AssistSkillDescriptionLabel;
	public UILabel copperCostLabel;
	public UILabel copperHasLabel;
	public UILabel contributeCostLabel;
	public UILabel contributeHasLabel;
	public GameObject LearningBtnPos;
	public GameObject FastLearningBtnPos;
	public GameObject contributeIcon2;
	public GameObject contributeIcon1;

	public void Setup (Transform root)
	{
		AssistSkillCellGrid = root.Find("LeftGroup/AssistSkillScrollView/AssistSkillCellGrid").GetComponent<UIGrid>();
		AssistSkillInfoTitleLabel = root.Find("RightGroup/1_AssistSkillInfoGroup/AssistSkillInfoTitleLabel").GetComponent<UILabel>();
		AssistSkillDescriptionLabel = root.Find("RightGroup/1_AssistSkillInfoGroup/AssistSkillDescriptionScrollView/AssistSkillDescriptionLabel").GetComponent<UILabel>();
		copperCostLabel = root.Find("RightGroup/3_UpgradeConditionsGroup/copperCostLabel").GetComponent<UILabel>();
		copperHasLabel = root.Find("RightGroup/3_UpgradeConditionsGroup/copperHasLabel").GetComponent<UILabel>();
		contributeCostLabel = root.Find("RightGroup/3_UpgradeConditionsGroup/contributeCostLabel").GetComponent<UILabel>();
		contributeHasLabel = root.Find("RightGroup/3_UpgradeConditionsGroup/contributeHasLabel").GetComponent<UILabel>();
		LearningBtnPos = root.Find("RightGroup/LearningBtnPos").gameObject;
		FastLearningBtnPos = root.Find("RightGroup/FastLearningBtnPos").gameObject;
		contributeIcon2 = root.Find("RightGroup/3_UpgradeConditionsGroup/contributeIcon2").gameObject;
		contributeIcon1 = root.Find("RightGroup/3_UpgradeConditionsGroup/contributeIcon1").gameObject;
	}
}
