//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for AssistSkillCell.
/// </summary>
public class AssistSkillCell : BaseView
{
	public UISprite IconSprite;
	public UIButton IconSpriteBtn;
	public UILabel CountLbl;

	public void Setup (Transform root)
	{
		IconSprite = root.Find("IconSprite").GetComponent<UISprite>();
		IconSpriteBtn = root.Find("IconSprite").GetComponent<UIButton>();
		CountLbl = root.Find("CountLbl").GetComponent<UILabel>();
	}
}
