//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for PracticeSkillView.
/// </summary>
public class PracticeSkillView : BaseView
{
	public UIGrid PracticeSkillCellGrid;
	public UILabel PracticeSkillInfoTitleLabel;
	public UILabel PracticeSkillDescriptionLabel;
	public UIToggle PracticeToggle;
	public UIButton TipsButton;
	public UILabel UpgradeTitleLabel;
	public UILabel ConsumptionLabel;
	public UILabel HaveLabel;
	public UILabel ExpLabel;
	public GameObject FastLearningBtnPos;
	public GameObject LearningBtnPos;
	public UIButton PracticeToggleBtn;

	public void Setup (Transform root)
	{
		PracticeSkillCellGrid = root.Find("LeftGroup/PracticeSkillScrollView/PracticeSkillCellGrid").GetComponent<UIGrid>();
		PracticeSkillInfoTitleLabel = root.Find("RightGroup/1_PracticeSkillInfoGroup/PracticeSkillInfoTitleLabel").GetComponent<UILabel>();
		PracticeSkillDescriptionLabel = root.Find("RightGroup/1_PracticeSkillInfoGroup/PracticeSkillDescriptionScrollView/PracticeSkillDescriptionLabel").GetComponent<UILabel>();
		PracticeToggle = root.Find("RightGroup/2_RelationGroup/PracticeToggle").GetComponent<UIToggle>();
		TipsButton = root.Find("RightGroup/2_RelationGroup/TipsButton").GetComponent<UIButton>();
		UpgradeTitleLabel = root.Find("RightGroup/3_UpgradeConditionsGroup/UpgradeTitleLabel").GetComponent<UILabel>();
		ConsumptionLabel = root.Find("RightGroup/3_UpgradeConditionsGroup/ConsumptionLabel").GetComponent<UILabel>();
		HaveLabel = root.Find("RightGroup/3_UpgradeConditionsGroup/HaveLabel").GetComponent<UILabel>();
		ExpLabel = root.Find("RightGroup/3_UpgradeConditionsGroup/ExpLabel").GetComponent<UILabel>();
		FastLearningBtnPos = root.Find("RightGroup/FastLearningBtnPos").gameObject;
		LearningBtnPos = root.Find("RightGroup/LearningBtnPos").gameObject;
		PracticeToggleBtn = root.Find("RightGroup/2_RelationGroup/PracticeToggle").GetComponent<UIButton>();
	}
}
