//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for PracticeSkillCell.
/// </summary>
public class PracticeSkillCell : BaseView
{
	public UISprite IconSprite;
	public UILabel LvLabel;
	public UILabel NameLabel;
	public UILabel TypeLabel;
	public UIButton SelectBtn;
	public UISprite SelectSprite;
	public GameObject PracticeIconSprite;

	public void Setup (Transform root)
	{
		IconSprite = root.Find("IconSprite").GetComponent<UISprite>();
		LvLabel = root.Find("LvLabel").GetComponent<UILabel>();
		NameLabel = root.Find("NameLabel").GetComponent<UILabel>();
		TypeLabel = root.Find("TypeLabel").GetComponent<UILabel>();
	SelectBtn = root.GetComponent<UIButton>();
	SelectSprite = root.GetComponent<UISprite>();
		PracticeIconSprite = root.Find("PracticeIconSprite").gameObject;
	}
}
