//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for SkillTipsView.
/// </summary>
public class SkillTipsView : BaseView
{
	public UISprite IconSprite;
	public UILabel NameLabel;
	public UILabel SkillDescriptionLbl;
	public UISprite ContentBg;
	public UIAnchor posAnchor;

	public void Setup (Transform root)
	{
		IconSprite = root.Find("ContentBg/TopGroup/IconSprite").GetComponent<UISprite>();
		NameLabel = root.Find("ContentBg/TopGroup/NameLabel").GetComponent<UILabel>();
		SkillDescriptionLbl = root.Find("ContentBg/SkillDescriptionLbl").GetComponent<UILabel>();
		ContentBg = root.Find("ContentBg").GetComponent<UISprite>();
		posAnchor = root.Find("ContentBg").GetComponent<UIAnchor>();
	}
}
