//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for HyperlinkItemCell.
/// </summary>
public class HyperlinkItemCell : BaseView
{
	public UILabel DescriptionLbl;
	public UIButton Btn;
	public UISprite Bg;

	public void Setup (Transform root)
	{
		DescriptionLbl = root.Find("Label").GetComponent<UILabel>();
	Btn = root.GetComponent<UIButton>();
		Bg = root.Find("Background").GetComponent<UISprite>();
	}
}
