//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for MultipleSelectionView.
/// </summary>
public class MultipleSelectionView : BaseView
{
	public UIAnchor viewAnchor;
	public UISprite bgSprite;
	public UIGrid btnGrid;
	public Transform btnGridTrans;
	public GameObject selectBtnPrefab;
	public UIPanel uiPanel;
	public UISprite arrowSprite;

	public void Setup (Transform root)
	{
	viewAnchor = root.GetComponent<UIAnchor>();
		bgSprite = root.Find("ContentBg").GetComponent<UISprite>();
		btnGrid = root.Find("ContentBg/ButtonGrid").GetComponent<UIGrid>();
		btnGridTrans = root.Find("ContentBg/ButtonGrid");
		selectBtnPrefab = root.Find("ContentBg/ButtonGrid/selectBtn").gameObject;
	uiPanel = root.GetComponent<UIPanel>();
		arrowSprite = root.Find("Arrow").GetComponent<UISprite>();
	}
}
