//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for PropertyInfoWidget.
/// </summary>
public class PropertyInfoWidget : BaseView
{
	public UILabel titleLbl;
	public UIButton titleBtn;
	public UISprite contentBg;
	public UILabel valLbl;
	public UILabel extraInfoLbl;

	public void Setup (Transform root)
	{
		titleLbl = root.Find("bgSprite/titleBg/titleLbl").GetComponent<UILabel>();
		titleBtn = root.Find("bgSprite/titleBg").GetComponent<UIButton>();
		contentBg = root.Find("bgSprite").GetComponent<UISprite>();
		valLbl = root.Find("bgSprite/valueBg/valLbl").GetComponent<UILabel>();
		extraInfoLbl = root.Find("bgSprite/extraInfoLbl").GetComponent<UILabel>();
	}
}
