//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for ToggleWidget.
/// </summary>
public class ToggleWidget : BaseView
{
	public UIButton btn;
	public UILabel label;
	public GameObject hook;

	public void Setup (Transform root)
	{
	btn = root.GetComponent<UIButton>();
		label = root.Find("Label").GetComponent<UILabel>();
		hook = root.Find("hookBg/hook").gameObject;
	}
}
