//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for TypeCellPrefabView.
/// </summary>
public class TypeCellPrefabView : BaseView
{
	public UILabel TypeNameLabel_UILabel;
	public UIButton TypeCellPrefabView_UIButton;
	public UISprite TypeBgSprite_UISprite;
	public UISprite TypeSelectSprite_UISprite;
	public Transform SubSprite_Transform;

	public void Setup (Transform root)
	{
		TypeNameLabel_UILabel = root.Find("TypeNameLabel").GetComponent<UILabel>();
	TypeCellPrefabView_UIButton = root.GetComponent<UIButton>();
		TypeBgSprite_UISprite = root.Find("TypeBgSprite").GetComponent<UISprite>();
		TypeSelectSprite_UISprite = root.Find("TypeSelectSprite").GetComponent<UISprite>();
		SubSprite_Transform = root.Find("SubSprite");
	}
}
