//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for BattleSkillSelectView.
/// </summary>
public class BattleSkillSelectView : BaseView
{
	public UITable Table;
	public UISprite BGSprite_UISprite;
	public UIButton CloseBtn_UIButton;

	public void Setup (Transform root)
	{
		Table = root.Find("Table").GetComponent<UITable>();
		BGSprite_UISprite = root.Find("BGSprite").GetComponent<UISprite>();
		CloseBtn_UIButton = root.Find("CloseBtn").GetComponent<UIButton>();
	}
}
