//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for PlayerInfoItemCell.
/// </summary>
public class PlayerInfoItemCell : BaseView
{
	public UILabel From_LevelLbl;
	public GameObject RelationObj;
	public UILabel NameLbl;
	public UIButton MoreBtn;
	public UISprite iconFace;
	public UIButton ClickBtn;
	public UISprite Bg;
	public UISprite RedPoint;

	public void Setup (Transform root)
	{
		From_LevelLbl = root.Find("From_Level").GetComponent<UILabel>();
		RelationObj = root.Find("Relation").gameObject;
		NameLbl = root.Find("NameLbl").GetComponent<UILabel>();
		MoreBtn = root.Find("MoreBtn").GetComponent<UIButton>();
		iconFace = root.Find("iconBg/icon").GetComponent<UISprite>();
	ClickBtn = root.GetComponent<UIButton>();
		Bg = root.Find("Bg").GetComponent<UISprite>();
		RedPoint = root.Find("RedPoint").GetComponent<UISprite>();
	}
}
