// **********************************************************************
// Copyright (c) 2013 Baoyugame. All rights reserved.
// File     :  KDTSServerMessageList.cs
// Author   : wenlin
// Created  : 2014/7/2 
// Purpose  : 
// **********************************************************************
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;


public class KDTSServerMessageList
{
	//gservice
	public string gservice;

	//host
	public string host;

	//登录http连接，传合作方sid和选择服进行登录，返回我方token
	//#参数: comeFrom渠道标识,serviceId服务器序号,sid渠道登录会话串,uid渠道帐号ID
	//#返回: json, 例如{"token":"cccccccccccccc"}	
	public string loginUrl;

	//#获取订单
	//#参数: comefrom渠道标识,serviceId服务器序号,uid渠道帐号ID
	//#返回: 纯文本订单ID,需要trim()
	public string payUrl;

	public List<KDTSServerInfo> list = null;

	public KDTSServerMessageList ()
	{
	}
}

