//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for WindowPrefab.
/// </summary>
public class WindowPrefab : BaseView
{
	public UILabel TitleLabel;
	public UILabel InfoLabel;
	public UIButton CancelButton;
	public UILabel CancelLabel;
	public UIButton OKButton;
	public UILabel OKLabel;

	public void Setup (Transform root)
	{
		TitleLabel = root.Find("ContentFrame/TitleLabel").GetComponent<UILabel>();
		InfoLabel = root.Find("ContentFrame/ContentBg/InfoLabel").GetComponent<UILabel>();
		CancelButton = root.Find("ContentFrame/CancelButton").GetComponent<UIButton>();
		CancelLabel = root.Find("ContentFrame/CancelButton/CancelLabel").GetComponent<UILabel>();
		OKButton = root.Find("ContentFrame/OKButton").GetComponent<UIButton>();
		OKLabel = root.Find("ContentFrame/OKButton/OKLabel").GetComponent<UILabel>();
	}
}
