//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for BackpackItemCell.
/// </summary>
public class BackpackItemCell : BaseView
{
	public UISprite LockSprite;

	public void Setup (Transform root)
	{
		LockSprite = root.Find("LockSprite").GetComponent<UISprite>();
	}
}
