//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for EquipmentCell.
/// </summary>
public class EquipmentCell : BaseView
{
	public UISprite PartIconSprite;

	public void Setup (Transform root)
	{
		PartIconSprite = root.Find("PartIconSprite").GetComponent<UISprite>();
	}
}
