//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for ItemsContainerView.
/// </summary>
public class ItemsContainerView : BaseView
{
	public UIGrid TabsGroup;
	public UIScrollView ContainerScrollView;
	public UICenterOnChild ItemContainerCenterOnChild;
	public UIPageGroup PageGroup;
	public UIGrid ItemContainerGrid;

	public void Setup (Transform root)
	{
		TabsGroup = root.Find("TabsGroup").GetComponent<UIGrid>();
		ContainerScrollView = root.Find("Container").GetComponent<UIScrollView>();
		ItemContainerCenterOnChild = root.Find("Container/ItemContainerGrid").GetComponent<UICenterOnChild>();
		PageGroup = root.Find("PageGroup").GetComponent<UIPageGroup>();
		ItemContainerGrid = root.Find("Container/ItemContainerGrid").GetComponent<UIGrid>();
	}
}
