//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for ItemCell.
/// </summary>
public class ItemCell : BaseView
{
	public UISprite SelectSprite;
	public UILabel CountLabel;
	public UISprite IconSprite;
	public UISprite ItemCellBg;
	public GameObject DragDropItem;
	public UIButton ItemCellBtn;
	public UIButton DragDropItemBtn;

	public void Setup (Transform root)
	{
		SelectSprite = root.Find("SelectSprite").GetComponent<UISprite>();
		CountLabel = root.Find("DragDropItem/CountLabel").GetComponent<UILabel>();
		IconSprite = root.Find("DragDropItem/IconSprite").GetComponent<UISprite>();
	ItemCellBg = root.GetComponent<UISprite>();
		DragDropItem = root.Find("DragDropItem").gameObject;
	ItemCellBtn = root.GetComponent<UIButton>();
		DragDropItemBtn = root.Find("DragDropItem").GetComponent<UIButton>();
	}
}
