//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for TradeCenterView.
/// </summary>
public class TradeCenterView : BaseView
{
	public UILabel MoneyLbl_UILabel;
	public UILabel PriceLbl_UILabel;
	public UIButton BuyButton_UIButton;
	public Transform BackpackPos_Transform;
	public UIGrid TypeListGrid_UIGrid;
	public UIGrid ItemListGrid_UIGrid;
	public UIScrollView ScrollView_UIScrollView;
	public UIScrollView TypeScrollView_UIScrollView;

	public void Setup (Transform root)
	{
		MoneyLbl_UILabel = root.Find("MoneyInfo/valueBg/valLbl").GetComponent<UILabel>();
		PriceLbl_UILabel = root.Find("PriceInfo/valueBg/valLbl").GetComponent<UILabel>();
		BuyButton_UIButton = root.Find("BuyButton").GetComponent<UIButton>();
		BackpackPos_Transform = root.Find("BackpackPos");
		TypeListGrid_UIGrid = root.Find("TypeListGroup/TypeScrollView/TypeListGrid").GetComponent<UIGrid>();
		ItemListGrid_UIGrid = root.Find("ItemListGroup/ScrollView/ItemListGrid").GetComponent<UIGrid>();
		ScrollView_UIScrollView = root.Find("ItemListGroup/ScrollView").GetComponent<UIScrollView>();
		TypeScrollView_UIScrollView = root.Find("TypeListGroup/TypeScrollView").GetComponent<UIScrollView>();
	}
}
