//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for CharacterPropertyView.
/// </summary>
public class CharacterPropertyView : BaseView
{
	public UISprite icon;
	public UILabel lvLbl;
	public UISlider hpSlider;
	public UISlider mpSlider;
	public UISlider spSlider;
	public UIGrid buffGrid;
	public UIButton iconBtn;
	public UISprite sp_foreground_UISprite;
	public UIButton PlayerPropertyInfo_UIButton;
	public GameObject mainUIBuffIcon;

	public void Setup (Transform root)
	{
		icon = root.Find("PlayerIconBg/PlayerIcon").GetComponent<UISprite>();
		lvLbl = root.Find("PlayerIconBg/Label").GetComponent<UILabel>();
		hpSlider = root.Find("PlayerPropertyInfo/HpSlider").GetComponent<UISlider>();
		mpSlider = root.Find("PlayerPropertyInfo/MpSlider").GetComponent<UISlider>();
		spSlider = root.Find("PlayerPropertyInfo/SpSlider").GetComponent<UISlider>();
		buffGrid = root.Find("PlayerPropertyInfo/BuffGroup").GetComponent<UIGrid>();
		iconBtn = root.Find("PlayerIconBg").GetComponent<UIButton>();
		sp_foreground_UISprite = root.Find("PlayerPropertyInfo/SpSlider/foreground").GetComponent<UISprite>();
		PlayerPropertyInfo_UIButton = root.Find("PlayerPropertyInfo").GetComponent<UIButton>();
		mainUIBuffIcon = root.Find("PlayerPropertyInfo/BuffGroup/mainUIBuffIcon").gameObject;
	}
}
