//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for MainUIExpandContentView.
/// </summary>
public class MainUIExpandContentView : BaseView
{
	public TweenPosition posTweener;
	public TweenAlpha alphaTweener;
	public UIButton taskBtn;
	public UIButton teamBtn;
	public GameObject taskTabContent;
	public GameObject teamTabContent;
	public UIGrid teamItemGrid;
	public GameObject teamMatrixInfoRoot;
	public UILabel teamMatrixInfoLbl;
	public UISprite taskBtnSelectEffect;
	public UISprite teamBtnSelectEffect;
	public UIButton callOrAwayBtn;
	public UILabel callOrAwayBtnLbl;
	public UIButton joinOrLeaveBtn;
	public UILabel joinOrLeaveBtnLbl;
	public UIWidget teamBtnGroupWidget;
	public UIScrollView itemScrollView;
	public UISprite TabCotentRoot_UISprite;
	public UITable taskItemTable_UITable;

	public void Setup (Transform root)
	{
	posTweener = root.GetComponent<TweenPosition>();
	alphaTweener = root.GetComponent<TweenAlpha>();
		taskBtn = root.Find("TabButtonRoot/TabBtn_Task").GetComponent<UIButton>();
		teamBtn = root.Find("TabButtonRoot/TabBtn_Team").GetComponent<UIButton>();
		taskTabContent = root.Find("TabCotentRoot/ScrollView/TabContent_Task").gameObject;
		teamTabContent = root.Find("TabCotentRoot/ScrollView/TabContent_Team").gameObject;
		teamItemGrid = root.Find("TabCotentRoot/ScrollView/TabContent_Team/teamItemGrid").GetComponent<UIGrid>();
		teamMatrixInfoRoot = root.Find("TabButtonRoot/TabBtn_Team/infoBg").gameObject;
		teamMatrixInfoLbl = root.Find("TabButtonRoot/TabBtn_Team/infoBg/infoLbl").GetComponent<UILabel>();
		taskBtnSelectEffect = root.Find("TabButtonRoot/TabBtn_Task/selectEffect").GetComponent<UISprite>();
		teamBtnSelectEffect = root.Find("TabButtonRoot/TabBtn_Team/selectEffect").GetComponent<UISprite>();
		callOrAwayBtn = root.Find("TabCotentRoot/teamBtnGroup/callOrAwayBtn").GetComponent<UIButton>();
		callOrAwayBtnLbl = root.Find("TabCotentRoot/teamBtnGroup/callOrAwayBtn/Label").GetComponent<UILabel>();
		joinOrLeaveBtn = root.Find("TabCotentRoot/teamBtnGroup/joinOrLeaveBtn").GetComponent<UIButton>();
		joinOrLeaveBtnLbl = root.Find("TabCotentRoot/teamBtnGroup/joinOrLeaveBtn/Label").GetComponent<UILabel>();
		teamBtnGroupWidget = root.Find("TabCotentRoot/teamBtnGroup").GetComponent<UIWidget>();
		itemScrollView = root.Find("TabCotentRoot/ScrollView").GetComponent<UIScrollView>();
		TabCotentRoot_UISprite = root.Find("TabCotentRoot").GetComponent<UISprite>();
		taskItemTable_UITable = root.Find("TabCotentRoot/ScrollView/TabContent_Task/taskItemTable").GetComponent<UITable>();
	}
}
