//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for PlayerHUDView.
/// </summary>
public class PlayerHUDView : BaseView
{
	public UILabel nameLbl;
	public UISprite fightFlagSprite;
	public UISpriteAnimation fightFlagSpriteAnimation;
	public UISprite teamFlagSprite;
	public UISpriteAnimation teamFlagSpriteAnimation;
	public UISpriteAnimation runFlagSpriteAnimation;
	public UISprite runFlagSprite;

	public void Setup (Transform root)
	{
		nameLbl = root.Find("nameLbl").GetComponent<UILabel>();
		fightFlagSprite = root.Find("fightFlag").GetComponent<UISprite>();
		fightFlagSpriteAnimation = root.Find("fightFlag").GetComponent<UISpriteAnimation>();
		teamFlagSprite = root.Find("teamFlag").GetComponent<UISprite>();
		teamFlagSpriteAnimation = root.Find("teamFlag").GetComponent<UISpriteAnimation>();
		runFlagSpriteAnimation = root.Find("runFlag").GetComponent<UISpriteAnimation>();
		runFlagSprite = root.Find("runFlag").GetComponent<UISprite>();
	}
}
