// **********************************************************************
// Copyright (c) 2013 Baoyugame. All rights reserved.
// File     :  PetWarehouseModule.cs
// Author   : willson
// Created  : 2015/3/20 
// Porpuse  : 
// **********************************************************************
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class ProxyPetWarehouseModule
{
	private const string NAME = "Prefabs/Module/PetWarehouseModule/PetWarehouseWinUI";
	
	public static void Open(int depath = UILayerType.DefaultModule)
	{
		PetWarehouseModel.Instance.Setup(()=>
		{
			GameObject ui = UIModuleManager.Instance.OpenFunModule(NAME,UILayerType.DefaultModule,true);
			var controller = ui.GetMissingComponent<PetWarehouseWinUIController>();
			controller.InitView();
		});

	}
	
	public static void Show()
	{
		UIModuleManager.Instance.OpenFunModule(NAME, UILayerType.DefaultModule, true);
	}
	
	public static void Hide()
	{
		UIModuleManager.Instance.HideModule(NAME);	
	}
	
	public static void Close()
	{
		UIModuleManager.Instance.CloseModule(NAME);
	}
}
