//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for PlayerChangeNameView.
/// </summary>
public class PlayerChangeNameView : BaseView
{
	public UILabel TipLabel;
	public UIButton CloseButton;
	public UIButton OkBtn;
	public UIButton CancelBtn;
	public UIInput NameInput;

	public void Setup (Transform root)
	{
		TipLabel = root.Find("TipLabel").GetComponent<UILabel>();
		CloseButton = root.Find("CloseButton").GetComponent<UIButton>();
		OkBtn = root.Find("OkBtn").GetComponent<UIButton>();
		CancelBtn = root.Find("CancelBtn").GetComponent<UIButton>();
		NameInput = root.Find("NameInput").GetComponent<UIInput>();
	}
}
