//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for BattleSummonView.
/// </summary>
public class BattleSummonView : BaseView
{
	public UIGrid PetListGrid_UIGrid;
	public UIButton SummonButton_UIButton;
	public UIButton CloseBtn_UIButton;
	public UILabel MagicValLbl_UILabel;
	public UILabel AttackValLbl_UILabel;
	public UILabel SpeedValLbl_UILabel;
	public UILabel MpValLbl_UILabel;
	public UILabel DefenseValLbl_UILabel;
	public UIGrid SkillGrid_UIGrid;
	public UILabel BattleInfoLabel_UILabel;
	public UILabel HpValLbl_UILabel;
	public UILabel SummonLabel_UILabel;

	public void Setup (Transform root)
	{
		PetListGrid_UIGrid = root.Find("RightSprite/ScrollView/PetListGrid").GetComponent<UIGrid>();
		SummonButton_UIButton = root.Find("RightSprite/SummonButton").GetComponent<UIButton>();
		CloseBtn_UIButton = root.Find("CloseBtn").GetComponent<UIButton>();
		MagicValLbl_UILabel = root.Find("LeftSprite/InfoGrid/MagicTitleInfoCell/valueBg/MagicValLbl").GetComponent<UILabel>();
		AttackValLbl_UILabel = root.Find("LeftSprite/InfoGrid/AttackTitleInfoCell/valueBg/AttackValLbl").GetComponent<UILabel>();
		SpeedValLbl_UILabel = root.Find("LeftSprite/InfoGrid/SpeedTitleInfoCell/valueBg/SpeedValLbl").GetComponent<UILabel>();
		MpValLbl_UILabel = root.Find("LeftSprite/InfoGrid/MpTitleInfoCell/valueBg/MpValLbl").GetComponent<UILabel>();
		DefenseValLbl_UILabel = root.Find("LeftSprite/InfoGrid/DefenseTitleInfoCell/valueBg/DefenseValLbl").GetComponent<UILabel>();
		SkillGrid_UIGrid = root.Find("LeftSprite/SkillGrid").GetComponent<UIGrid>();
		BattleInfoLabel_UILabel = root.Find("LeftSprite/BattleInfoLabel").GetComponent<UILabel>();
		HpValLbl_UILabel = root.Find("LeftSprite/InfoGrid/HpTitleInfoCell/valueBg/HpValLbl").GetComponent<UILabel>();
		SummonLabel_UILabel = root.Find("RightSprite/SummonButton/Label").GetComponent<UILabel>();
	}
}
