//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for BiddingWindowView.
/// </summary>
public class BiddingWindowView : BaseView
{
	public UIButton CloseButton_UIButton;
	public UIButton BiddingButton_UIButton;
	public UILabel CountLabel_UILabel;
	public UISprite IconSprite_UISprite;
	public UILabel NameLabel_UILabel;
	public UILabel IncrementLabel_UILabel;
	public UIButton CutbackButton_UIButton;
	public UIButton IncreaseButton_UIButton;
	public UILabel TotalPriceValLbl_UILabel;
	public UILabel PriceValLbl_UILabel;

	public void Setup (Transform root)
	{
		CloseButton_UIButton = root.Find("CloseButton").GetComponent<UIButton>();
		BiddingButton_UIButton = root.Find("Content/BiddingButton").GetComponent<UIButton>();
		CountLabel_UILabel = root.Find("Content/ItemCell/CountLabel").GetComponent<UILabel>();
		IconSprite_UISprite = root.Find("Content/ItemCell/IconSprite").GetComponent<UISprite>();
		NameLabel_UILabel = root.Find("Content/ItemCell/NameLabel").GetComponent<UILabel>();
		IncrementLabel_UILabel = root.Find("Content/IncrementLabel").GetComponent<UILabel>();
		CutbackButton_UIButton = root.Find("Content/PriceCellWidget/ModifiedBtn/CutbackButton").GetComponent<UIButton>();
		IncreaseButton_UIButton = root.Find("Content/PriceCellWidget/ModifiedBtn/IncreaseButton").GetComponent<UIButton>();
		TotalPriceValLbl_UILabel = root.Find("Content/TotalPriceCellWidget/valueBg/TotalPriceValLbl").GetComponent<UILabel>();
		PriceValLbl_UILabel = root.Find("Content/PriceCellWidget/valueBg/PriceValLbl").GetComponent<UILabel>();
	}
}
