//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for CharacterInfoWidget.
/// </summary>
public class CharacterInfoWidget : BaseView
{
	public UISprite icon;
	public UISprite iconFlag;
	public UISprite indexSprite;
	public UILabel infoLbl;
	public GameObject selectEffect;
	public UISprite statusSprite;
	public UISprite bgSprite;
	public GameObject indexBgGo;

	public void Setup (Transform root)
	{
		icon = root.Find("iconBg/iconSprite").GetComponent<UISprite>();
		iconFlag = root.Find("iconBg/iconFlag").GetComponent<UISprite>();
		indexSprite = root.Find("iconBg/bgSprite/indexSprite").GetComponent<UISprite>();
		infoLbl = root.Find("infoLbl").GetComponent<UILabel>();
		selectEffect = root.Find("selectSprite").gameObject;
		statusSprite = root.Find("statusSprite").GetComponent<UISprite>();
	bgSprite = root.GetComponent<UISprite>();
		indexBgGo = root.Find("iconBg/bgSprite").gameObject;
	}
}
