//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for FilterItemWidget.
/// </summary>
public class FilterItemWidget : BaseView
{
	public UILabel nameLbl;
	public UIToggle filterToggle;

	public void Setup (Transform root)
	{
		nameLbl = root.Find("nameLbl").GetComponent<UILabel>();
		filterToggle = root.Find("toggle").GetComponent<UIToggle>();
	}
}
