//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for LayoutItemWidget.
/// </summary>
public class LayoutItemWidget : BaseView
{
	public UILabel nameLbl;
	public GameObject selectedEffect;
	public UIButton itemBtn;

	public void Setup (Transform root)
	{
		nameLbl = root.Find("nameLbl").GetComponent<UILabel>();
		selectedEffect = root.Find("selected").gameObject;
	itemBtn = root.GetComponent<UIButton>();
	}
}
