//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for PlayerTeamView.
/// </summary>
public class PlayerTeamView : BaseView
{
	public UIButton joinOrLeaveBtn;
	public UIGrid teamMemberGrid;
	public UIButton closeBtn;
	public GameObject autoGroupContentRoot;
	public GameObject matrixContentRoot;
	public UIGrid applicationItemGrid;
	public UILabel matchInfoLbl;
	public UIGrid rankFilterItemGrid;
	public UIGrid channelFilterItemGrid;
	public UIButton matchBtn;
	public UILabel applicationListTitle;
	public UIButton callOrAwayBtn;
	public UIGrid tabBtnGrid;
	public UILabel matchBtnLbl;
	public UILabel callOrAwayBtnLbl;
	public UILabel joinOrLeaveBtnLbl;
	public UIGrid acquiredLayoutItemGrid;
	public UIGrid moreLayoutItemGrid;
	public UILabel layoutDescLbl;
	public GameObject matrixItemPanel;
	public UIWidget acquiredMatrixListWidget;
	public UIButton moreMatrixInfoBtn;
	public GameObject matrixSelectedEffect;

	public void Setup (Transform root)
	{
		joinOrLeaveBtn = root.Find("ContentFrame/ContentBg/LeftGroup/JoinOrLeaveBtn").GetComponent<UIButton>();
		teamMemberGrid = root.Find("ContentFrame/ContentBg/LeftGroup/TeamMemberGrid").GetComponent<UIGrid>();
		closeBtn = root.Find("ContentFrame/CloseBtn").GetComponent<UIButton>();
		autoGroupContentRoot = root.Find("ContentFrame/ContentBg/RightGroup/TabContentRoot/TabContent_AutoGroup").gameObject;
		matrixContentRoot = root.Find("ContentFrame/ContentBg/RightGroup/TabContentRoot/TabContent_Matrix").gameObject;
		applicationItemGrid = root.Find("ContentFrame/ContentBg/RightGroup/TabContentRoot/TabContent_AutoGroup/ApplicationItemList/scrollView/itemListGrid").GetComponent<UIGrid>();
		matchInfoLbl = root.Find("ContentFrame/ContentBg/RightGroup/TabContentRoot/TabContent_AutoGroup/ApplicationItemList/MatchInfoBg/MatchingInfoLbl").GetComponent<UILabel>();
		rankFilterItemGrid = root.Find("ContentFrame/ContentBg/RightGroup/TabContentRoot/TabContent_AutoGroup/RightGroup/RankFilterItemList/scrollView/itemListGrid").GetComponent<UIGrid>();
		channelFilterItemGrid = root.Find("ContentFrame/ContentBg/RightGroup/TabContentRoot/TabContent_AutoGroup/RightGroup/ChannelFilterItemList/scrollView/itemListGrid").GetComponent<UIGrid>();
		matchBtn = root.Find("ContentFrame/ContentBg/RightGroup/TabContentRoot/TabContent_AutoGroup/RightGroup/MatchBtn").GetComponent<UIButton>();
		applicationListTitle = root.Find("ContentFrame/ContentBg/RightGroup/TabContentRoot/TabContent_AutoGroup/ApplicationItemList/titleBg/titleLbl").GetComponent<UILabel>();
		callOrAwayBtn = root.Find("ContentFrame/ContentBg/RightGroup/TabContentRoot/TabContent_Matrix/RightGroup/CallOrAwayBtn").GetComponent<UIButton>();
		tabBtnGrid = root.Find("ContentFrame/ContentBg/RightGroup/TabBtnGrid").GetComponent<UIGrid>();
		matchBtnLbl = root.Find("ContentFrame/ContentBg/RightGroup/TabContentRoot/TabContent_AutoGroup/RightGroup/MatchBtn/Label").GetComponent<UILabel>();
		callOrAwayBtnLbl = root.Find("ContentFrame/ContentBg/RightGroup/TabContentRoot/TabContent_Matrix/RightGroup/CallOrAwayBtn/Label").GetComponent<UILabel>();
		joinOrLeaveBtnLbl = root.Find("ContentFrame/ContentBg/LeftGroup/JoinOrLeaveBtn/Label").GetComponent<UILabel>();
		acquiredLayoutItemGrid = root.Find("ContentFrame/ContentBg/RightGroup/TabContentRoot/TabContent_Matrix/RightGroup/AcquiredMatrixList/scrollView/itemListGrid").GetComponent<UIGrid>();
		moreLayoutItemGrid = root.Find("ContentFrame/ContentBg/RightGroup/TabContentRoot/TabContent_Matrix/RightGroup/MoreMatrixList/scrollView/itemListGrid").GetComponent<UIGrid>();
		layoutDescLbl = root.Find("ContentFrame/ContentBg/RightGroup/TabContentRoot/TabContent_Matrix/MatrixLayoutGroup/descInfo/descLbl").GetComponent<UILabel>();
		matrixItemPanel = root.Find("ContentFrame/ContentBg/RightGroup/TabContentRoot/TabContent_Matrix/MatrixLayoutGroup/matrixBg/matrixItemPanel").gameObject;
		acquiredMatrixListWidget = root.Find("ContentFrame/ContentBg/RightGroup/TabContentRoot/TabContent_Matrix/RightGroup/AcquiredMatrixList").GetComponent<UIWidget>();
		moreMatrixInfoBtn = root.Find("ContentFrame/ContentBg/RightGroup/TabContentRoot/TabContent_Matrix/RightGroup/MoreMatrixList/titleBg").GetComponent<UIButton>();
		matrixSelectedEffect = root.Find("ContentFrame/ContentBg/RightGroup/TabContentRoot/TabContent_Matrix/MatrixLayoutGroup/matrixBg/matrixSelectedEffect").gameObject;
	}
}
