//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for AutoFramWinUI.
/// </summary>
public class AutoFramWinUI : BaseView
{
	public UIGrid MapGrid;
	public UIButton CloseBtn;
	public GameObject FrozenPos;
	public GameObject AutoFramBtnPos;
	public GameObject ReceivePos;
	public UILabel GetPointLabel;
	public UILabel PointLabel;
	public UIButton AutoFramTipsButton;
	public UIButton ReceiveTipsButton;
	public UIScrollView MapPanelScrollView;
	public GameObject TipsPanel;
	public UILabel TipsTitlelbl;
	public UILabel TipsInfolbl;
	public UIEventTrigger TipsBoxCollider;
	public GameObject MonsterPanel;
	public UILabel SceneMaplbl;
	public UIEventTrigger MonsterBoxCollider;
	public UIGrid MonsterGrid;

	public void Setup (Transform root)
	{
		MapGrid = root.Find("MapPanel/Grid").GetComponent<UIGrid>();
		CloseBtn = root.Find("CloseBtn").GetComponent<UIButton>();
		FrozenPos = root.Find("BtuGroup/FrozenPos").gameObject;
		AutoFramBtnPos = root.Find("BtuGroup/AutoFramBtnPos").gameObject;
		ReceivePos = root.Find("BtuGroup/ReceivePos").gameObject;
		GetPointLabel = root.Find("BtuGroup/GetPointLabel").GetComponent<UILabel>();
		PointLabel = root.Find("BtuGroup/PointLabel").GetComponent<UILabel>();
		AutoFramTipsButton = root.Find("BtuGroup/AutoFramTipsButton").GetComponent<UIButton>();
		ReceiveTipsButton = root.Find("BtuGroup/ReceiveTipsButton").GetComponent<UIButton>();
		MapPanelScrollView = root.Find("MapPanel").GetComponent<UIScrollView>();
		TipsPanel = root.Find("TipsPanel").gameObject;
		TipsTitlelbl = root.Find("TipsPanel/TipsTitlelbl").GetComponent<UILabel>();
		TipsInfolbl = root.Find("TipsPanel/TipsInfolbl").GetComponent<UILabel>();
		TipsBoxCollider = root.Find("TipsPanel/TipsBoxCollider").GetComponent<UIEventTrigger>();
		MonsterPanel = root.Find("MonsterPanel").gameObject;
		SceneMaplbl = root.Find("MonsterPanel/SceneMaplbl").GetComponent<UILabel>();
		MonsterBoxCollider = root.Find("MonsterPanel/MonsterBoxCollider").GetComponent<UIEventTrigger>();
		MonsterGrid = root.Find("MonsterPanel/MonsterGrid").GetComponent<UIGrid>();
	}
}
