//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for MyTradePetInfoCell.
/// </summary>
public class MyTradePetInfoCell : BaseView
{
	public UISprite SelectSprite;
	public UILabel NameLabel;
	public UILabel LvLabel;
	public UILabel PriceLabel;
	public GameObject OptBtnPos;

	public void Setup (Transform root)
	{
		SelectSprite = root.Find("SelectSprite").GetComponent<UISprite>();
		NameLabel = root.Find("NameLabel").GetComponent<UILabel>();
		LvLabel = root.Find("LvLabel").GetComponent<UILabel>();
		PriceLabel = root.Find("PriceLabel").GetComponent<UILabel>();
		OptBtnPos = root.Find("OptBtnPos").gameObject;
	}
}
