//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for PetShopWinUI.
/// </summary>
public class PetShopWinUI : BaseView
{
	public UIButton CloseBtn;
	public UIGrid PetLvGrid;
	public UIGrid PetInfoGrid;
	public UIGrid MyPetGrid;
	public UILabel priceLbl;
	public UILabel hasLbl;
	public GameObject OptBtnPos;

	public void Setup (Transform root)
	{
		CloseBtn = root.Find("bgGroup/CloseBtn").GetComponent<UIButton>();
		PetLvGrid = root.Find("LeftGroup/PetLvScrollView/PetLvGrid").GetComponent<UIGrid>();
		PetInfoGrid = root.Find("LeftGroup/PetInfoScrollView/PetInfoGrid").GetComponent<UIGrid>();
		MyPetGrid = root.Find("RightGroup/MyPetScrollView/MyPetGrid").GetComponent<UIGrid>();
		priceLbl = root.Find("RightGroup/WealthGroup/1_copper/bgSprite/valueBg/valLbl").GetComponent<UILabel>();
		hasLbl = root.Find("RightGroup/WealthGroup/2_silver/bgSprite/valueBg/valLbl").GetComponent<UILabel>();
		OptBtnPos = root.Find("RightGroup/WealthGroup/OptBtnPos").gameObject;
	}
}
