//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for TradePetInfoCell.
/// </summary>
public class TradePetInfoCell : BaseView
{
	public UISprite SelectSprite;
	public UILabel NameLabel;
	public UILabel PriceLabel;
	public UILabel CountLabel;

	public void Setup (Transform root)
	{
		SelectSprite = root.Find("SelectSprite").GetComponent<UISprite>();
		NameLabel = root.Find("NameLabel").GetComponent<UILabel>();
		PriceLabel = root.Find("PriceLabel").GetComponent<UILabel>();
		CountLabel = root.Find("CountLabel").GetComponent<UILabel>();
	}
}
