//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for TradePetLvCell.
/// </summary>
public class TradePetLvCell : BaseView
{
	public UISprite SelectSprite;
	public UILabel NameLabel;

	public void Setup (Transform root)
	{
		SelectSprite = root.Find("SelectSprite").GetComponent<UISprite>();
		NameLabel = root.Find("NameLabel").GetComponent<UILabel>();
	}
}
