//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for BaseItemCellWidget.
/// </summary>
public class BaseItemCellWidget : BaseView
{
	public UIButton itemBtn;
	public UISprite icon;
	public UILabel iconLbl;
	public GameObject selectEffect;
	public UILabel itemLbl;
	public GameObject redDot;

	public void Setup (Transform root)
	{
	itemBtn = root.GetComponent<UIButton>();
		icon = root.Find("icon").GetComponent<UISprite>();
		iconLbl = root.Find("iconLbl").GetComponent<UILabel>();
		selectEffect = root.Find("selectEffect").gameObject;
		itemLbl = root.Find("itemLbl").GetComponent<UILabel>();
		redDot = root.Find("redDot").gameObject;
	}
}
