//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for AutoFramMapCell.
/// </summary>
public class AutoFramMapCell : BaseView
{
	public UIButton SpriteBgBtn;
	public UILabel MapNameLabel;
	public UILabel MapLvLabel;
	public GameObject ModelAnchor;
	public UIButton TipsButton;
	public UISprite SpriteBg;

	public void Setup (Transform root)
	{
		SpriteBgBtn = root.Find("SpriteBg").GetComponent<UIButton>();
		MapNameLabel = root.Find("MapNameLabel").GetComponent<UILabel>();
		MapLvLabel = root.Find("MapLvLabel").GetComponent<UILabel>();
		ModelAnchor = root.Find("ModelAnchor").gameObject;
		TipsButton = root.Find("TipsButton").GetComponent<UIButton>();
		SpriteBg = root.Find("SpriteBg").GetComponent<UISprite>();
	}
}
