//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for MonsterIconCell.
/// </summary>
public class MonsterIconCell : BaseView
{
	public UILabel NameLabel;
	public UISprite IconSprite;

	public void Setup (Transform root)
	{
		NameLabel = root.Find("NameLabel").GetComponent<UILabel>();
		IconSprite = root.Find("IconSprite").GetComponent<UISprite>();
	}
}
