//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for RequestLoadingTipPrefab.
/// </summary>
public class RequestLoadingTipPrefab : BaseView
{
	public Transform LoadingGroup_Transform;
	public UILabel TipLabel_UILabel;
	public UISprite CircleSprite_UISprite;
	public UISprite BgSprite_UISprite;

	public void Setup (Transform root)
	{
		LoadingGroup_Transform = root.Find("LoadingGroup");
		TipLabel_UILabel = root.Find("LoadingGroup/TipLabel").GetComponent<UILabel>();
		CircleSprite_UISprite = root.Find("LoadingGroup/CircleSprite").GetComponent<UISprite>();
		BgSprite_UISprite = root.Find("LoadingGroup/BgSprite").GetComponent<UISprite>();
	}
}
