//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for SceneFadeEffectPrefab.
/// </summary>
public class SceneFadeEffectPrefab : BaseView
{
	public UITexture bgTexture;
	public UISlider loadingSlider;
	public UILabel tipLbl;
	public TweenAlpha alphaTween;
	public UILabel loadingLbl;

	public void Setup (Transform root)
	{
		bgTexture = root.Find("bgTexture").GetComponent<UITexture>();
		loadingSlider = root.Find("loadingSlider").GetComponent<UISlider>();
		tipLbl = root.Find("tipBg/tipLbl").GetComponent<UILabel>();
		alphaTween = root.Find("fadeBg").GetComponent<TweenAlpha>();
		loadingLbl = root.Find("loadingSlider/LoadingLabel").GetComponent<UILabel>();
	}
}
