//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for SystemSettingView.
/// </summary>
public class SystemSettingView : BaseView
{
	public UIToggle MusicCheckbox_UIToggle;
	public UISlider MusicSlider_UISlider;
	public UILabel MusicValue_UILabel;
	public UIToggle SoundCheckbox_UIToggle;
	public UISlider SoundSlider_UISlider;
	public UILabel SoundValue_UILabel;
	public UISlider VoiceSlider_UISlider;
	public UILabel VoiceValue_UILabel;
	public UIToggle LensCheckbox_UIToggle;
	public UIToggle LocationCheckbox_UIToggle;
	public UIToggle TrafficCheckbox_UIToggle;
	public UIToggle ContingentCheckbox_UIToggle;
	public UIToggle FactionCheckbox_UIToggle;
	public UIToggle FriendsCheckbox_UIToggle;
	public UIToggle StrangerCheckbox_UIToggle;
	public UIToggle WorldCheckbox_UIToggle;
	public UIToggle EnergyConservingCheckbox_UIToggle;

	public void Setup (Transform root)
	{
		MusicCheckbox_UIToggle = root.Find("MusicVolume/MusicCheckbox").GetComponent<UIToggle>();
		MusicSlider_UISlider = root.Find("MusicVolume/MusicSlider").GetComponent<UISlider>();
		MusicValue_UILabel = root.Find("MusicVolume/MusicRight/MusicValue").GetComponent<UILabel>();
		SoundCheckbox_UIToggle = root.Find("SoundVolume/SoundCheckbox").GetComponent<UIToggle>();
		SoundSlider_UISlider = root.Find("SoundVolume/SoundSlider").GetComponent<UISlider>();
		SoundValue_UILabel = root.Find("SoundVolume/SoundRight/SoundValue").GetComponent<UILabel>();
		VoiceSlider_UISlider = root.Find("VoiceSetting/VoiceSlider").GetComponent<UISlider>();
		VoiceValue_UILabel = root.Find("VoiceSetting/VoiceRight/VoiceValue").GetComponent<UILabel>();
		LensCheckbox_UIToggle = root.Find("GroupSub/LensCheckbox").GetComponent<UIToggle>();
		LocationCheckbox_UIToggle = root.Find("GroupSub/LocationCheckbox").GetComponent<UIToggle>();
		TrafficCheckbox_UIToggle = root.Find("GroupSub/TrafficCheckbox").GetComponent<UIToggle>();
		ContingentCheckbox_UIToggle = root.Find("GroupThr/ContingentCheckbox").GetComponent<UIToggle>();
		FactionCheckbox_UIToggle = root.Find("GroupThr/FactionCheckbox").GetComponent<UIToggle>();
		FriendsCheckbox_UIToggle = root.Find("GroupThr/FriendsCheckbox").GetComponent<UIToggle>();
		StrangerCheckbox_UIToggle = root.Find("GroupThr/StrangerCheckbox").GetComponent<UIToggle>();
		WorldCheckbox_UIToggle = root.Find("GroupThr/WorldCheckbox").GetComponent<UIToggle>();
		EnergyConservingCheckbox_UIToggle = root.Find("GroupSub/EnergyConservingCheckbox").GetComponent<UIToggle>();
	}
}
