//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for ShopWinUI.
/// </summary>
public class ShopWinUI : BaseView
{
	public UISprite TitleSprite;
	public UIButton CloseBtn;
	public UIGrid ItemsGrid;
	public UILabel ItemTIpsLabel;
	public UIGrid ItemTabsGrid;
	public UIButton BuyWealthButton;
	public UILabel RefreshTipsLabel;
	public GameObject PayBtnPos;
	public GameObject BuyBtnPos;
	public UILabel HaveLbl;
	public UIEventListener AddBtnEventListener;
	public UIEventListener SubBtnEventListener;
	public UIEventTrigger countBtn;
	public UILabel CountLbl;
	public UILabel PriceLbl;
	public UIGrid TabsGrid;
	public UIScrollView ItemScrollView;
	public UISprite PriceIconSprite;
	public UISprite HaveIconSprite;

	public void Setup (Transform root)
	{
		TitleSprite = root.Find("bgGroup/Sprite/TitleSprite").GetComponent<UISprite>();
		CloseBtn = root.Find("bgGroup/CloseBtn").GetComponent<UIButton>();
		ItemsGrid = root.Find("LeftGroup/ItemPanel/ItemsGrid").GetComponent<UIGrid>();
		ItemTIpsLabel = root.Find("RightGroup/ItemTipsBg/ItemTIpsLabel").GetComponent<UILabel>();
		ItemTabsGrid = root.Find("LeftGroup/ItemTabsGrid").GetComponent<UIGrid>();
		BuyWealthButton = root.Find("RightGroup/PriceGrid/HaveInfo/bgSprite/valueBg/BuyWealthButton").GetComponent<UIButton>();
		RefreshTipsLabel = root.Find("bgGroup/RefreshTipsLabel").GetComponent<UILabel>();
		PayBtnPos = root.Find("RightGroup/BtnGrid/PayBtnPos").gameObject;
		BuyBtnPos = root.Find("RightGroup/BtnGrid/BuyBtnPos").gameObject;
		HaveLbl = root.Find("RightGroup/PriceGrid/HaveInfo/bgSprite/valueBg/valLbl").GetComponent<UILabel>();
		AddBtnEventListener = root.Find("RightGroup/PriceGrid/CountInfo/bgSprite/valueBg/AddButton").GetComponent<UIEventListener>();
		SubBtnEventListener = root.Find("RightGroup/PriceGrid/CountInfo/bgSprite/valueBg/SubButton").GetComponent<UIEventListener>();
		countBtn = root.Find("RightGroup/PriceGrid/CountInfo/bgSprite/valueBg/valLbl").GetComponent<UIEventTrigger>();
		CountLbl = root.Find("RightGroup/PriceGrid/CountInfo/bgSprite/valueBg/valLbl").GetComponent<UILabel>();
		PriceLbl = root.Find("RightGroup/PriceGrid/PriceInfo/bgSprite/valueBg/valLbl").GetComponent<UILabel>();
		TabsGrid = root.Find("bgGroup/TabsGrid").GetComponent<UIGrid>();
		ItemScrollView = root.Find("LeftGroup/ItemPanel").GetComponent<UIScrollView>();
		PriceIconSprite = root.Find("RightGroup/PriceGrid/PriceInfo/bgSprite/valueBg/Sprite").GetComponent<UISprite>();
		HaveIconSprite = root.Find("RightGroup/PriceGrid/HaveInfo/bgSprite/valueBg/Sprite").GetComponent<UISprite>();
	}
}
