//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for PPDetailView.
/// </summary>
public class PPDetailView : BaseView
{
	public UIButton closeBtn;
	public UIButton saveBtn;
	public UIButton cancelBtn;
	public UIGrid infoItemGrid;
	public UIEventTrigger bgMaskEventTrigger;

	public void Setup (Transform root)
	{
		closeBtn = root.Find("CloseBtn").GetComponent<UIButton>();
		saveBtn = root.Find("ContentBg/SaveBtn").GetComponent<UIButton>();
		cancelBtn = root.Find("ContentBg/CancelBtn").GetComponent<UIButton>();
		infoItemGrid = root.Find("ContentBg/PPItemGrid").GetComponent<UIGrid>();
		bgMaskEventTrigger = root.Find("BgMask").GetComponent<UIEventTrigger>();
	}
}
