//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for BattleSummonPetCell.
/// </summary>
public class BattleSummonPetCell : BaseView
{
	public UISprite ItemIcon_UISprite;
	public UISprite StatusSprite_UISprite;
	public UILabel NameLabel_UILabel;
	public UILabel InfoLabel_UILabel;
	public UIButton BattleSummonPetCell_UIButton;
	public UISprite CellSelectSprite_UISprite;

	public void Setup (Transform root)
	{
		ItemIcon_UISprite = root.Find("ItemCell/ItemIcon").GetComponent<UISprite>();
		StatusSprite_UISprite = root.Find("ItemCell/StatusSprite").GetComponent<UISprite>();
		NameLabel_UILabel = root.Find("NameLabel").GetComponent<UILabel>();
		InfoLabel_UILabel = root.Find("InfoLabel").GetComponent<UILabel>();
	BattleSummonPetCell_UIButton = root.GetComponent<UIButton>();
		CellSelectSprite_UISprite = root.Find("CellSelectSprite").GetComponent<UISprite>();
	}
}
