//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for NpcHUDView.
/// </summary>
public class NpcHUDView : BaseView
{
	public UIFollowTarget BottomFollow_UIFollowTarget;
	public UIFollowTarget TopFollow_UIFollowTarget;
	public UILabel nameLbl_UILabel;
	public UISprite missionType_UISprite;
	public UISprite fightFlag_UISprite;
	public UISpriteAnimation fightFlag_UISpriteAnimation;

	public void Setup (Transform root)
	{
		BottomFollow_UIFollowTarget = root.Find("BottomFollow").GetComponent<UIFollowTarget>();
		TopFollow_UIFollowTarget = root.Find("TopFollow").GetComponent<UIFollowTarget>();
		nameLbl_UILabel = root.Find("BottomFollow/nameLbl").GetComponent<UILabel>();
		missionType_UISprite = root.Find("TopFollow/missionType").GetComponent<UISprite>();
		fightFlag_UISprite = root.Find("TopFollow/fightFlag").GetComponent<UISprite>();
		fightFlag_UISpriteAnimation = root.Find("TopFollow/fightFlag").GetComponent<UISpriteAnimation>();
	}
}
