//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for WorldMapView.
/// </summary>
public class WorldMapView : BaseView
{
	public UIButton CloseButton;
	public UITable WorldTable;

	public void Setup (Transform root)
	{
		CloseButton = root.Find("CloseButton").GetComponent<UIButton>();
		WorldTable = root.Find("WorldTable").GetComponent<UITable>();
	}
}
