//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for ChatMsgView.
/// </summary>
public class ChatMsgView : BaseView
{
	public UILabel msgLbl;

	public void Setup (Transform root)
	{
	msgLbl = root.GetComponent<UILabel>();
	}
}
