//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for FlowerPropsView.
/// </summary>
public class FlowerPropsView : BaseView
{
	public UIGrid FriendItemGrid;
	public UIPageGrid itemGrid;
	public UIButton GiftBtn;
	public UIButton CloseBtn;

	public void Setup (Transform root)
	{
		FriendItemGrid = root.Find("Left/Content/ItemCellView/ItemGrid").GetComponent<UIGrid>();
		itemGrid = root.Find("Right/Content/PropPanel/itemGrid").GetComponent<UIPageGrid>();
		GiftBtn = root.Find("Right/Content/GiftBtn").GetComponent<UIButton>();
		CloseBtn = root.Find("Right/Content/CloseBtn").GetComponent<UIButton>();
	}
}
