//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for GiftPropsView.
/// </summary>
public class GiftPropsView : BaseView
{
	public UIButton Tips;
	public UILabel ValuesLbl;
	public UILabel CountLbl;
	public UILabel DescriptionLbl;
	public UIButton CloseBtn;
	public UIButton GiftBtn;
	public UILabel GiveBtnLbl;
	public UILabel NameLbl;
	public UIPageGrid itemGrid;

	public void Setup (Transform root)
	{
		Tips = root.Find("ItemInfo/Tips").GetComponent<UIButton>();
		ValuesLbl = root.Find("ItemInfo/Worth/Values").GetComponent<UILabel>();
		CountLbl = root.Find("ItemInfo/Number/Count").GetComponent<UILabel>();
		DescriptionLbl = root.Find("ItemInfo/Description").GetComponent<UILabel>();
		CloseBtn = root.Find("Content/CloseBtn").GetComponent<UIButton>();
		GiftBtn = root.Find("Content/GiftBtn").GetComponent<UIButton>();
		GiveBtnLbl = root.Find("Content/GiftBtn/Label").GetComponent<UILabel>();
		NameLbl = root.Find("ItemInfo/NameLbl").GetComponent<UILabel>();
		itemGrid = root.Find("Content/PropPanel/itemGrid").GetComponent<UIPageGrid>();
	}
}
