//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for GiftItemCell.
/// </summary>
public class GiftItemCell : BaseView
{
	public UIButton GiftItemCellBtn;
	public UIButton ReduceBtn;
	public UISprite IconSprite;
	public UILabel CountLabel;
	public GameObject SelectSpriteObj;
	public GameObject DragDropItemObj;

	public void Setup (Transform root)
	{
	GiftItemCellBtn = root.GetComponent<UIButton>();
		ReduceBtn = root.Find("ReduceBtn").GetComponent<UIButton>();
		IconSprite = root.Find("DragDropItem/IconSprite").GetComponent<UISprite>();
		CountLabel = root.Find("DragDropItem/CountLabel").GetComponent<UILabel>();
		SelectSpriteObj = root.Find("SelectSprite").gameObject;
		DragDropItemObj = root.Find("DragDropItem").gameObject;
	}
}
