//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for WealthCell.
/// </summary>
public class WealthCell : BaseView
{
	public UIButton WealthCellBtn;
	public UISprite WealthIcon;
	public UILabel ValueLabel;
	public UILabel CostLabel;
	public UISprite WealthSprite;
	public UISprite CostSprite;

	public void Setup (Transform root)
	{
	WealthCellBtn = root.GetComponent<UIButton>();
		WealthIcon = root.Find("WealthIcon").GetComponent<UISprite>();
		ValueLabel = root.Find("ValueLabel").GetComponent<UILabel>();
		CostLabel = root.Find("CostLabel").GetComponent<UILabel>();
		WealthSprite = root.Find("WealthSprite").GetComponent<UISprite>();
		CostSprite = root.Find("CostSprite").GetComponent<UISprite>();
	}
}
