//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for MiniWorldMapView.
/// </summary>
public class MiniWorldMapView : BaseView
{
	public UIButton CloseBtn;
	public Transform PlaceGroup;
	public UIButton BackMyFactionBtn;
	public UIButton CurrMapBtn;
	public UILabel CurrMapBtnLbl;
	public UIButton GoHomeBtn;
	public GameObject HeroSprite;

	public void Setup (Transform root)
	{
		CloseBtn = root.Find("CloseBtn").GetComponent<UIButton>();
		PlaceGroup = root.Find("PlaceGroup");
		BackMyFactionBtn = root.Find("BackMyFactionBtn").GetComponent<UIButton>();
		CurrMapBtn = root.Find("CurrMapBtn").GetComponent<UIButton>();
		CurrMapBtnLbl = root.Find("CurrMapBtn/CurrMapBtnLbl").GetComponent<UILabel>();
		GoHomeBtn = root.Find("GoHomeBtn").GetComponent<UIButton>();
		HeroSprite = root.Find("HeroSprite").gameObject;
	}
}
