//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for AssistSkillMakeWinUI.
/// </summary>
public class AssistSkillMakeWinUI : BaseView
{
	public UIButton CloseBtn;
	public UILabel VigourValLbl;
	public UILabel ItemNameLabel;
	public GameObject ItemPos;
	public UILabel UsageDescLabel;
	public GameObject OptBtnPos;
	public UIButton LBtn;
	public UIButton RBtn;

	public void Setup (Transform root)
	{
		CloseBtn = root.Find("CloseBtn").GetComponent<UIButton>();
		VigourValLbl = root.Find("vigour/bgSprite/valueBg/VigourValLbl").GetComponent<UILabel>();
		ItemNameLabel = root.Find("ItemNameLabel").GetComponent<UILabel>();
		ItemPos = root.Find("ItemPos").gameObject;
		UsageDescLabel = root.Find("UsageDescLabel").GetComponent<UILabel>();
		OptBtnPos = root.Find("OptBtnPos").gameObject;
		LBtn = root.Find("LBtn").GetComponent<UIButton>();
		RBtn = root.Find("RBtn").GetComponent<UIButton>();
	}
}
