//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for BattleView.
/// </summary>
public class BattleView : BaseView
{
	public Transform MainUI;
	public UIButton AutoButton;
	public UIButton AttackButton;
	public UIButton SkillButton;
	public UIButton DefenseButton;
	public UIButton ManualButton;
	public UILabel RoundTimeLabel;
	public UISprite RoundWatingSprite;
	public UILabel RoundLabel;
	public UISprite TipSprite;
	public UILabel TipLabel;
	public UISprite TargetSelectSprite;
	public UILabel SkillNameLabel;
	public UIButton CancelButton;
	public UILabel CharactorLabel_UILabel;
	public UIButton CatchButton;
	public UIButton ProtectButton;
	public UIButton RetreatButton;
	public UIButton SummonButton;
	public UIButton ItemButton;
	public UIButton StuntButton;
	public UIGrid BottomButtonGrid_UIGrid;
	public UIGrid RightButtonGrid_UIGrid;
	public UIButton PlayerDefaultSkillButton;
	public UIButton PetDefaultSkillButton;
	public Transform BottomRightAnchor_Transform;
	public Transform Anchor_BottomRight_Transform;
	public Transform RoundInfoGroup_Transform;
	public UISprite PlayerIconSprite_UISprite;
	public UISprite EnemyIconSprite_UISprite;
	public UIButton DefaultSkillButton;
	public UISprite PlayerDefaultSkillSprite_UISprite;
	public UISprite PetDefaultSkillSprite_UISprite;
	public GameObject BottomRightBg;
	public GameObject AutoSkillSelectGroup;
	public UISprite AutoSkillSelectBg_UISprite;
	public UIGrid AutoSkillSelectGrid_UIGrid;
	public UILabel AutoSkillSelectTipLabel_UILabel;
	public GameObject PlayerDefaultSkillIconGroup;
	public UISprite PlayerDefaultSkillIcon_UISprite;
	public UILabel PlayerDefaultSkillNameLabel_UILabel;
	public GameObject PetDefaultSkillIconGroup;
	public UISprite PetDefaultSkillIcon_UISprite;
	public UILabel PetDefaultSkillNameLabel_UILabel;
	public UILabel DefaultSkilllNameLabel_UILabel;
	public GameObject StatusSprite;
	public UILabel NameLabel_UILabel;
	public UILabel MPLabel_UILabel;
	public UILabel HPLabel_UILabel;
	public UILabel SPLabel_UILabel;
	public GameObject SPGroup;
	public UISprite StatusSprite_UISprite;

	public void Setup (Transform root)
	{
		MainUI = root.Find("MainUI");
		AutoButton = root.Find("MainUI/Anchor_BottomRight/BottomRightAnchor/AutoButton").GetComponent<UIButton>();
		AttackButton = root.Find("MainUI/Anchor_BottomRight/RightButtonGrid/AttackButton").GetComponent<UIButton>();
		SkillButton = root.Find("MainUI/Anchor_BottomRight/RightButtonGrid/SkillButton").GetComponent<UIButton>();
		DefenseButton = root.Find("MainUI/Anchor_BottomRight/BottomButtonGrid/DefenseButton").GetComponent<UIButton>();
		ManualButton = root.Find("MainUI/Anchor_BottomRight/BottomRightAnchor/ManualButton").GetComponent<UIButton>();
		RoundTimeLabel = root.Find("MainUI/Anchor_Top/RoundTimeLabel").GetComponent<UILabel>();
		RoundWatingSprite = root.Find("MainUI/Anchor_Top/RoundWatingSprite").GetComponent<UISprite>();
		RoundLabel = root.Find("MainUI/Anchor_Top/RoundInfoGroup/RoundLabel").GetComponent<UILabel>();
		TipSprite = root.Find("MainUI/Anchor_Center/TipSprite").GetComponent<UISprite>();
		TipLabel = root.Find("MainUI/Anchor_Center/TipSprite/TipLabel").GetComponent<UILabel>();
		TargetSelectSprite = root.Find("MainUI/Anchor_Center/TargetSelectSprite").GetComponent<UISprite>();
		SkillNameLabel = root.Find("MainUI/Anchor_Center/TargetSelectSprite/SkillNameLabel").GetComponent<UILabel>();
		CancelButton = root.Find("MainUI/Anchor_Center/TargetSelectSprite/CancelButton").GetComponent<UIButton>();
		CharactorLabel_UILabel = root.Find("MainUI/Anchor_Center/TargetSelectSprite/CharactorLabel").GetComponent<UILabel>();
		CatchButton = root.Find("MainUI/Anchor_BottomRight/BottomButtonGrid/CatchButton").GetComponent<UIButton>();
		ProtectButton = root.Find("MainUI/Anchor_BottomRight/BottomButtonGrid/ProtectButton").GetComponent<UIButton>();
		RetreatButton = root.Find("MainUI/Anchor_BottomRight/BottomButtonGrid/RetreatButton").GetComponent<UIButton>();
		SummonButton = root.Find("MainUI/Anchor_BottomRight/BottomButtonGrid/SummonButton").GetComponent<UIButton>();
		ItemButton = root.Find("MainUI/Anchor_BottomRight/RightButtonGrid/ItemButton").GetComponent<UIButton>();
		StuntButton = root.Find("MainUI/Anchor_BottomRight/RightButtonGrid/StuntButton").GetComponent<UIButton>();
		BottomButtonGrid_UIGrid = root.Find("MainUI/Anchor_BottomRight/BottomButtonGrid").GetComponent<UIGrid>();
		RightButtonGrid_UIGrid = root.Find("MainUI/Anchor_BottomRight/RightButtonGrid").GetComponent<UIGrid>();
		PlayerDefaultSkillButton = root.Find("MainUI/Anchor_BottomRight/BottomRightAnchor/PlayerDefaultSkillButton").GetComponent<UIButton>();
		PetDefaultSkillButton = root.Find("MainUI/Anchor_BottomRight/BottomRightAnchor/PetDefaultSkillButton").GetComponent<UIButton>();
		BottomRightAnchor_Transform = root.Find("MainUI/Anchor_BottomRight/BottomRightAnchor");
		Anchor_BottomRight_Transform = root.Find("MainUI/Anchor_BottomRight");
		RoundInfoGroup_Transform = root.Find("MainUI/Anchor_Top/RoundInfoGroup");
		PlayerIconSprite_UISprite = root.Find("MainUI/Anchor_Top/RoundInfoGroup/PlayerIconSprite").GetComponent<UISprite>();
		EnemyIconSprite_UISprite = root.Find("MainUI/Anchor_Top/RoundInfoGroup/EnemyIconSprite").GetComponent<UISprite>();
		DefaultSkillButton = root.Find("MainUI/Anchor_BottomRight/RightButtonGrid/DefaultSkillButton").GetComponent<UIButton>();
		PlayerDefaultSkillSprite_UISprite = root.Find("MainUI/Anchor_BottomRight/BottomRightAnchor/PlayerDefaultSkillButton/PlayerDefaultSkillSprite").GetComponent<UISprite>();
		PetDefaultSkillSprite_UISprite = root.Find("MainUI/Anchor_BottomRight/BottomRightAnchor/PetDefaultSkillButton/PetDefaultSkillSprite").GetComponent<UISprite>();
		BottomRightBg = root.Find("MainUI/Anchor_BottomRight/BottomRightAnchor/BottomRightBg").gameObject;
		AutoSkillSelectGroup = root.Find("MainUI/Anchor_BottomRight/BottomRightAnchor/AutoSkillSelectGroup").gameObject;
		AutoSkillSelectBg_UISprite = root.Find("MainUI/Anchor_BottomRight/BottomRightAnchor/AutoSkillSelectGroup/AutoSkillSelectBg").GetComponent<UISprite>();
		AutoSkillSelectGrid_UIGrid = root.Find("MainUI/Anchor_BottomRight/BottomRightAnchor/AutoSkillSelectGroup/AutoSkillSelectGrid").GetComponent<UIGrid>();
		AutoSkillSelectTipLabel_UILabel = root.Find("MainUI/Anchor_BottomRight/BottomRightAnchor/AutoSkillSelectGroup/AutoSkillSelectTipLabel").GetComponent<UILabel>();
		PlayerDefaultSkillIconGroup = root.Find("MainUI/Anchor_BottomRight/BottomRightAnchor/PlayerDefaultSkillButton/PlayerDefaultSkillIconGroup").gameObject;
		PlayerDefaultSkillIcon_UISprite = root.Find("MainUI/Anchor_BottomRight/BottomRightAnchor/PlayerDefaultSkillButton/PlayerDefaultSkillIconGroup/PlayerDefaultSkillIcon").GetComponent<UISprite>();
		PlayerDefaultSkillNameLabel_UILabel = root.Find("MainUI/Anchor_BottomRight/BottomRightAnchor/PlayerDefaultSkillButton/PlayerDefaultSkillIconGroup/PlayerDefaultSkillNameLabel").GetComponent<UILabel>();
		PetDefaultSkillIconGroup = root.Find("MainUI/Anchor_BottomRight/BottomRightAnchor/PetDefaultSkillButton/PetDefaultSkillIconGroup").gameObject;
		PetDefaultSkillIcon_UISprite = root.Find("MainUI/Anchor_BottomRight/BottomRightAnchor/PetDefaultSkillButton/PetDefaultSkillIconGroup/PetDefaultSkillIcon").GetComponent<UISprite>();
		PetDefaultSkillNameLabel_UILabel = root.Find("MainUI/Anchor_BottomRight/BottomRightAnchor/PetDefaultSkillButton/PetDefaultSkillIconGroup/PetDefaultSkillNameLabel").GetComponent<UILabel>();
		DefaultSkilllNameLabel_UILabel = root.Find("MainUI/Anchor_BottomRight/RightButtonGrid/DefaultSkillButton/DefaultSkilllNameLabel").GetComponent<UILabel>();
		StatusSprite = root.Find("MainUI/Anchor_Center/StatusSprite").gameObject;
		NameLabel_UILabel = root.Find("MainUI/Anchor_Center/StatusSprite/NameLabel").GetComponent<UILabel>();
		MPLabel_UILabel = root.Find("MainUI/Anchor_Center/StatusSprite/MPGroup/MPLabel").GetComponent<UILabel>();
		HPLabel_UILabel = root.Find("MainUI/Anchor_Center/StatusSprite/HPGroup/HPLabel").GetComponent<UILabel>();
		SPLabel_UILabel = root.Find("MainUI/Anchor_Center/StatusSprite/SPGroup/SPLabel").GetComponent<UILabel>();
		SPGroup = root.Find("MainUI/Anchor_Center/StatusSprite/SPGroup").gameObject;
		StatusSprite_UISprite = root.Find("MainUI/Anchor_Center/StatusSprite").GetComponent<UISprite>();
	}
}
