//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
using com.nucleus.h1.logic.whole.modules.trade.data;
using System;

/// <summary>
/// Generates a safe wrapper for TradeCenterTypeCellPrefab.
/// </summary>
public class TradeCenterTypeCellPrefab : BaseView
{
	public UILabel Label_UILabel;
	public UIButton TradeCenterTypeCellPrefab_UIButton;
	public UISprite SelectSprite_UISprite;
	public UISprite BgSprite_UISprite;
	public Transform SubSprite_Transform;

	public void Setup (Transform root)
	{
		Label_UILabel = root.Find("Label").GetComponent<UILabel>();
		TradeCenterTypeCellPrefab_UIButton = root.GetComponent<UIButton>();
		SelectSprite_UISprite = root.Find("SelectSprite").GetComponent<UISprite>();
		BgSprite_UISprite = root.Find("BgSprite").GetComponent<UISprite>();
		SubSprite_Transform = root.Find("SubSprite");
	}
	
	private TradeMenu _menu;
	public event Action<TradeCenterTypeCellPrefab> _OnCellSelect;
	
	public void SetData(TradeMenu menu, Action<TradeCenterTypeCellPrefab> OnCellSelect)
	{
		_menu = menu;
		
		_OnCellSelect = OnCellSelect;
		Setup (this.transform);
		
		SelectSprite_UISprite.gameObject.SetActive (false);
		
		bool tIsMainMenu = menu.parentId == 0;
		BgSprite_UISprite.alpha = tIsMainMenu? 1 : 0;
		SubSprite_Transform.gameObject.SetActive(!tIsMainMenu);
		
		Label_UILabel.color = Color.white;
		Label_UILabel.effectStyle = tIsMainMenu? UILabel.Effect.Outline8 : UILabel.Effect.None;
		Label_UILabel.text = string.Format("[{0}]{1}[-]", tIsMainMenu? "fff9e3" : "6f3e1a", _menu.name);
		
		EventDelegate.Set (TradeCenterTypeCellPrefab_UIButton.onClick, OnClickCell);
	}
	
	private void OnClickCell()
	{
		if (_OnCellSelect != null)
		{
			_OnCellSelect(this);
		}
	}
	
	public TradeMenu GetMenu()
	{
		return _menu;
	}
	
	public void Select(bool select)
	{
		if (_menu.parentId == 0)
		{
			BgSprite_UISprite.spriteName = select?"green-little-bone":"small-bone-under-lines";
		}
		else
		{
			SelectSprite_UISprite.gameObject.SetActive (select);
		}
	}
}
