//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for GuildsInfoWinUI.
/// </summary>
public class GuildsInfoWinUI : BaseView
{
	public UIButton CloseBtn;
	public GameObject GuildsInfoGroup;
	public GameObject GuildCreateGroup;
	public UIGrid GuildListGrid;
	public UILabel PurposeLabel;
	public UIButton AllApplyJoinButton;
	public UIButton ApplyJoinButton;
	public UIButton CallBossButton;
	public UIButton CreateButton;
	public UIInput GuildIDInput;
	public UIButton SearchGulidButton;
	public UIButton ApprenticeTipsButton;
	public UIInput GuildNameInput;
	public UILabel GuildNameLabel;
	public UIInput GuildPurposeInput;
	public UILabel GuildPurposeLabel;
	public UILabel TooMuchTipsLabel;
	public UILabel CostLabel;
	public GameObject OkBtnPos;
	public GameObject CancelBtnPos;

	public void Setup (Transform root)
	{
		CloseBtn = root.Find("bgGroup/CloseBtn").GetComponent<UIButton>();
		GuildsInfoGroup = root.Find("GuildsInfoGroup").gameObject;
		GuildCreateGroup = root.Find("GuildCreateGroup").gameObject;
		GuildListGrid = root.Find("GuildsInfoGroup/LeftGroup/GuildListScrollView/GuildListGrid").GetComponent<UIGrid>();
		PurposeLabel = root.Find("GuildsInfoGroup/RightGroup/PurposeGroup/PurposeLabel").GetComponent<UILabel>();
		AllApplyJoinButton = root.Find("GuildsInfoGroup/RightGroup/AllApplyJoinButton").GetComponent<UIButton>();
		ApplyJoinButton = root.Find("GuildsInfoGroup/RightGroup/ApplyJoinButton").GetComponent<UIButton>();
		CallBossButton = root.Find("GuildsInfoGroup/RightGroup/CallBossButton").GetComponent<UIButton>();
		CreateButton = root.Find("GuildsInfoGroup/RightGroup/CreateButton").GetComponent<UIButton>();
		GuildIDInput = root.Find("GuildsInfoGroup/BottomGroup/GuildIDInput").GetComponent<UIInput>();
		SearchGulidButton = root.Find("GuildsInfoGroup/BottomGroup/SearchGulidButton").GetComponent<UIButton>();
		ApprenticeTipsButton = root.Find("GuildsInfoGroup/BottomGroup/ApprenticeTipsButton").GetComponent<UIButton>();
		GuildNameInput = root.Find("GuildCreateGroup/GuildNameInput").GetComponent<UIInput>();
		GuildNameLabel = root.Find("GuildCreateGroup/GuildNameInput/GuildNameLabel").GetComponent<UILabel>();
		GuildPurposeInput = root.Find("GuildCreateGroup/GuildPurposeInput").GetComponent<UIInput>();
		GuildPurposeLabel = root.Find("GuildCreateGroup/GuildPurposeInput/GuildPurposeLabel").GetComponent<UILabel>();
		TooMuchTipsLabel = root.Find("GuildCreateGroup/TooMuchTipsLabel").GetComponent<UILabel>();
		CostLabel = root.Find("GuildCreateGroup/CostLabel").GetComponent<UILabel>();
		OkBtnPos = root.Find("GuildCreateGroup/OkBtnPos").gameObject;
		CancelBtnPos = root.Find("GuildCreateGroup/CancelBtnPos").gameObject;
	}
}
