//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for RoleCreateView.
/// </summary>
public class RoleCreateView : BaseView
{
	public UIButton StartGameButton;
	public UIButton ServerNameButton;
	public UILabel ServerNameLabel;
	public UILabel PlayerNameLabel;
	public UITable CharactorTable;
	public UITable FactionTable;

	public void Setup (Transform root)
	{
		StartGameButton = root.Find("StartGameButton").GetComponent<UIButton>();
		ServerNameButton = root.Find("ServerNameLabel").GetComponent<UIButton>();
		ServerNameLabel = root.Find("ServerNameLabel").GetComponent<UILabel>();
		PlayerNameLabel = root.Find("PlayerNameLabel").GetComponent<UILabel>();
		CharactorTable = root.Find("CharactorTable").GetComponent<UITable>();
		FactionTable = root.Find("FactionTable").GetComponent<UITable>();
	}
}
