//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for RankingTypeCell.
/// </summary>
public class RankingTypeCell : BaseView
{
	public UIButton RankingTypeCellBtn;
	public UISprite BtnBgSprite;
	public UILabel NameLabel;
	public GameObject SubSprite;
	public UISprite SelectSprite;

	public void Setup (Transform root)
	{
	RankingTypeCellBtn = root.GetComponent<UIButton>();
		BtnBgSprite = root.Find("BgSprite").GetComponent<UISprite>();
		NameLabel = root.Find("NameLabel").GetComponent<UILabel>();
		SubSprite = root.Find("SubSprite").gameObject;
		SelectSprite = root.Find("SubSprite/SelectSprite").GetComponent<UISprite>();
	}
}
