//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for RankingWinUI.
/// </summary>
public class RankingWinUI : BaseView
{
	public UIButton CloseBtn;
	public UIGrid RankingGrid;
	public UILabel RankingTipsLabel;

	public void Setup (Transform root)
	{
		CloseBtn = root.Find("bgGroup/CloseBtn").GetComponent<UIButton>();
		RankingGrid = root.Find("LeftGroup/RankingGrid").GetComponent<UIGrid>();
		RankingTipsLabel = root.Find("RightGroup/BgSprite/RankingTipsLabel").GetComponent<UILabel>();
	}
}
