//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for FactionSkillLearningView.
/// </summary>
public class FactionSkillLearningView : BaseView
{
	public UIGrid FactionSKillCellGrid;
	public UILabel FactionSkillDescriptionLabel;
	public UILabel FactionSkillInfoTitleLabel;
	public UILabel RelationTitleLabel;
	public UILabel UpgradeTitleLabel;
	public UILabel ConsumptionLabel;
	public UILabel HaveLabel;
	public GameObject AllBtnPos;
	public GameObject LearningBtnPos;
	public GameObject SubSkillGroup;
	public UILabel subSkillTipsLbl;

	public void Setup (Transform root)
	{
		FactionSKillCellGrid = root.Find("LeftGroup/FactionSKillScrollView/FactionSKillCellGrid").GetComponent<UIGrid>();
		FactionSkillDescriptionLabel = root.Find("RightGroup/1_FactionSkillInfoGroup/FactionSkillDescriptionScrollView/FactionSkillDescriptionLabel").GetComponent<UILabel>();
		FactionSkillInfoTitleLabel = root.Find("RightGroup/1_FactionSkillInfoGroup/FactionSkillInfoTitleLabel").GetComponent<UILabel>();
		RelationTitleLabel = root.Find("RightGroup/2_RelationGroup/RelationTitleLabel").GetComponent<UILabel>();
		UpgradeTitleLabel = root.Find("RightGroup/3_UpgradeConditionsGroup/UpgradeTitleLabel").GetComponent<UILabel>();
		ConsumptionLabel = root.Find("RightGroup/3_UpgradeConditionsGroup/ConsumptionLabel").GetComponent<UILabel>();
		HaveLabel = root.Find("RightGroup/3_UpgradeConditionsGroup/HaveLabel").GetComponent<UILabel>();
		AllBtnPos = root.Find("RightGroup/AllBtnPos").gameObject;
		LearningBtnPos = root.Find("RightGroup/LearningBtnPos").gameObject;
		SubSkillGroup = root.Find("RightGroup/2_RelationGroup/SubSkillGroup").gameObject;
		subSkillTipsLbl = root.Find("RightGroup/2_RelationGroup/subSkillTipsLbl").GetComponent<UILabel>();
	}
}
