//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for WealthBuyWinUI.
/// </summary>
public class WealthBuyWinUI : BaseView
{
	public UIButton CloseBtn;
	public UIGrid WealthGrid;

	public void Setup (Transform root)
	{
		CloseBtn = root.Find("BgGroup/CloseBtn").GetComponent<UIButton>();
		WealthGrid = root.Find("WealthGrid").GetComponent<UIGrid>();
	}
}
