//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for ActorPopoModule.
/// </summary>
public class ActorPopoModule : BaseView,IViewController
{
	private ActorPopoModuleView _view;

	#region IViewController implementation
	public void InitView ()
	{
		_view = this.gameObject.GetMissingComponent<ActorPopoModuleView>();
		_view.Setup (this.transform);
	}
	public void RegisterEvent ()
	{
	}
	public void Dispose ()
	{
	}
	#endregion

	private Transform _targetTransform;
	private Transform _myTransform;
	private float _offY;
	private Camera _showCamera;
	private long _id;

	public void Open (long id, Transform tran, string msg, Camera showCamera, float offY = 0)
	{
		_id = id;
		_myTransform = this.transform;
		_targetTransform = tran;
		_showCamera = showCamera;
		_offY = offY;

		_view.MsgLabel_UILabel.overflowMethod = UILabel.Overflow.ResizeFreely;

		_view.MsgLabel_UILabel.text = msg;

		SetBackgroundWith (_view.MsgLabel_UILabel.width + 8);

		if (_view.MsgLabel_UILabel.width > 220)
		{
			_view.MsgLabel_UILabel.width = 228;
			_view.MsgLabel_UILabel.overflowMethod = UILabel.Overflow.ResizeHeight;
			Invoke ("DelayAdjustHeight", 0.01f);
		}
		else
		{
			_view.MsgLabel_UILabel.overflowMethod = UILabel.Overflow.ResizeHeight;
			SetBackgroundHeight(_view.MsgLabel_UILabel.height + 8);
		}

		SetBackgroundWith(_view.MsgLabel_UILabel.width + 8);

		_view.MsgLabel_UILabel.transform.localPosition = new Vector3 (0f,_view.MsgLabel_UILabel.transform.localPosition.y, 0f);

		CancelInvoke ("DelayClose");
		Invoke ("DelayClose", 6f);
	}

	private void SetBackgroundWith(int width)
	{
		_view.BackgroundLeft_UISprite.width = width / 2;
		_view.BackgroundRight_UISprite.width = width / 2;
	}

	private void SetBackgroundHeight(int height)
	{
		height += 5;
		if (height < 35)
		{
			height = 35;
		}

		_view.BackgroundLeft_UISprite.height = height;
		_view.BackgroundRight_UISprite.height = height;
		_view.Tail_UISprite.height = height + 18;
	}

	private void DelayAdjustHeight()
	{
		SetBackgroundHeight (_view.MsgLabel_UILabel.height + 14);
	}

	void LateUpdate()
	{
		if ( _targetTransform == null )
			return;

		Vector3 position = _targetTransform.position;
		position.y = position.y + _offY;
		position= _showCamera.WorldToViewportPoint( position );
		position = UICamera.currentCamera.ViewportToWorldPoint( position );
		position.z = _myTransform.position.z;
		
		_myTransform.position = position;
	}

	private void DelayClose()
	{
		ProxyActorPopoModule.Close (_id);
	}

	void DestroyMe()
	{
		Destroy( gameObject );
	}
}
