//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for ActorPopoModuleView.
/// </summary>
public class ActorPopoModuleView : BaseView
{
	public UILabel MsgLabel_UILabel;
	public UISprite Tail_UISprite;
	public UISprite BackgroundLeft_UISprite;
	public UISprite BackgroundRight_UISprite;

	public void Setup (Transform root)
	{
		MsgLabel_UILabel = root.Find("MsgLabel").GetComponent<UILabel>();
		Tail_UISprite = root.Find("Tail").GetComponent<UISprite>();
		BackgroundLeft_UISprite = root.Find("BackgroundLeft").GetComponent<UISprite>();
		BackgroundRight_UISprite = root.Find("BackgroundRight").GetComponent<UISprite>();
	}
}
