//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for PetChangeNameView.
/// </summary>
public class PetChangeNameView : BaseView
{
	public UIInput nameInput;
	public UIButton defualtBtn;
	public UIButton confirmBtn;
	public UIButton cancelBtn;

	public void Setup (Transform root)
	{
		nameInput = root.Find("ContentBg/nameInput").GetComponent<UIInput>();
		defualtBtn = root.Find("ContentBg/ButtonGroup/defualtBtn").GetComponent<UIButton>();
		confirmBtn = root.Find("ContentBg/ButtonGroup/confirmBtn").GetComponent<UIButton>();
		cancelBtn = root.Find("ContentBg/ButtonGroup/cancelBtn").GetComponent<UIButton>();
	}
}
