//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for CrewMainView.
/// </summary>
public class CrewMainView : BaseView
{
	public UISprite contentTitleSprite;
	public GameObject BaseInfoGroup;
	public UISprite crewMemberGroupBg;
	public UIGrid crewItemGrid;
	public UIGrid rightTabBtnGrid;
	public GameObject TabContent_CrewMatrix;
	public GameObject TabContent_CrewProperty;
	public Transform modelAnchor;
	public UIButton closeBtn;
	public UIGrid atkConfigToggleGrid;
	public UIGrid defConfigToggleGrid;
	public GameObject matrixSelectedEffect;
	public GameObject matrixItemPanel;
	public UILabel matrixDescLbl;
	public UIGrid acquiredLayoutItemGrid;
	public UIGrid moreLayoutItemGrid;
	public UIButton restOrBattleBtn;
	public UILabel restOrBattleBtnLbl;
	public UIGrid eqItemGrid;
	public UIGrid crewInfoTabBtnGrid;
	public GameObject TabContent_BaseProperty;
	public GameObject TabContent_Aptitude;
	public GameObject TabContent_Skill;
	public PageScrollView propsItemGrid;
	public GameObject CrewTavernGroup;
	public UIWidget acquiredMatrixListWidget;
	public UIButton moreMatrixInfoBtn;
	public UISprite arrowSprite;

	public void Setup (Transform root)
	{
		contentTitleSprite = root.Find("ContentFrame/_titleBg/_titleSprite").GetComponent<UISprite>();
		BaseInfoGroup = root.Find("ContentFrame/ContentBg/BaseInfoGroup").gameObject;
		crewMemberGroupBg = root.Find("ContentFrame/ContentBg/BaseInfoGroup/CrewMemberGroup").GetComponent<UISprite>();
		crewItemGrid = root.Find("ContentFrame/ContentBg/BaseInfoGroup/CrewMemberGroup/CrewItemScrollView/CrewItemGrid").GetComponent<UIGrid>();
		rightTabBtnGrid = root.Find("ContentFrame/ContentBg/TabBtnGrid").GetComponent<UIGrid>();
		TabContent_CrewMatrix = root.Find("ContentFrame/ContentBg/BaseInfoGroup/TabContentGroup/TabContent_CrewMatrix").gameObject;
		TabContent_CrewProperty = root.Find("ContentFrame/ContentBg/BaseInfoGroup/TabContentGroup/TabContent_CrewProperty").gameObject;
		modelAnchor = root.Find("ContentFrame/ContentBg/BaseInfoGroup/TabContentGroup/TabContent_CrewProperty/CrewPropertyInfoGroup/TopInfoGroup/ModelAnchor");
		closeBtn = root.Find("ContentFrame/CloseBtn").GetComponent<UIButton>();
		atkConfigToggleGrid = root.Find("ContentFrame/ContentBg/BaseInfoGroup/TabContentGroup/TabContent_CrewMatrix/TopGroup/atkConfigGroup/atkConfigToggles").GetComponent<UIGrid>();
		defConfigToggleGrid = root.Find("ContentFrame/ContentBg/BaseInfoGroup/TabContentGroup/TabContent_CrewMatrix/TopGroup/defConfigGroup/defConfigToggles").GetComponent<UIGrid>();
		matrixSelectedEffect = root.Find("ContentFrame/ContentBg/BaseInfoGroup/TabContentGroup/TabContent_CrewMatrix/MatrixLayoutGroup/matrixBg/matrixSelectedEffect").gameObject;
		matrixItemPanel = root.Find("ContentFrame/ContentBg/BaseInfoGroup/TabContentGroup/TabContent_CrewMatrix/MatrixLayoutGroup/matrixBg/matrixItemPanel").gameObject;
		matrixDescLbl = root.Find("ContentFrame/ContentBg/BaseInfoGroup/TabContentGroup/TabContent_CrewMatrix/MatrixLayoutGroup/descInfo/descLbl").GetComponent<UILabel>();
		acquiredLayoutItemGrid = root.Find("ContentFrame/ContentBg/BaseInfoGroup/TabContentGroup/TabContent_CrewMatrix/RightGroup/AcquiredMatrixList/scrollView/itemListGrid").GetComponent<UIGrid>();
		moreLayoutItemGrid = root.Find("ContentFrame/ContentBg/BaseInfoGroup/TabContentGroup/TabContent_CrewMatrix/RightGroup/MoreMatrixList/scrollView/itemListGrid").GetComponent<UIGrid>();
		restOrBattleBtn = root.Find("ContentFrame/ContentBg/BaseInfoGroup/TabContentGroup/TabContent_CrewMatrix/RightGroup/restOrBattleBtn").GetComponent<UIButton>();
		restOrBattleBtnLbl = root.Find("ContentFrame/ContentBg/BaseInfoGroup/TabContentGroup/TabContent_CrewMatrix/RightGroup/restOrBattleBtn/Label").GetComponent<UILabel>();
		eqItemGrid = root.Find("ContentFrame/ContentBg/BaseInfoGroup/TabContentGroup/TabContent_CrewProperty/CrewPropertyInfoGroup/TopInfoGroup/EquipmentGroup").GetComponent<UIGrid>();
		crewInfoTabBtnGrid = root.Find("ContentFrame/ContentBg/BaseInfoGroup/TabContentGroup/TabContent_CrewProperty/CrewPropertyInfoGroup/BottomInfoGroup/TabBtnGrid").GetComponent<UIGrid>();
		TabContent_BaseProperty = root.Find("ContentFrame/ContentBg/BaseInfoGroup/TabContentGroup/TabContent_CrewProperty/CrewPropertyInfoGroup/BottomInfoGroup/TabContentRoot/TabContent_BaseProperty").gameObject;
		TabContent_Aptitude = root.Find("ContentFrame/ContentBg/BaseInfoGroup/TabContentGroup/TabContent_CrewProperty/CrewPropertyInfoGroup/BottomInfoGroup/TabContentRoot/TabContent_Aptitude").gameObject;
		TabContent_Skill = root.Find("ContentFrame/ContentBg/BaseInfoGroup/TabContentGroup/TabContent_CrewProperty/CrewPropertyInfoGroup/BottomInfoGroup/TabContentRoot/TabContent_Skill").gameObject;
		propsItemGrid = root.Find("ContentFrame/ContentBg/BaseInfoGroup/TabContentGroup/TabContent_CrewProperty/RightTabContentRoot/PropsItemScrollView/propsItemGrid").GetComponent<PageScrollView>();
		CrewTavernGroup = root.Find("ContentFrame/ContentBg/CrewTavernGroup").gameObject;
		acquiredMatrixListWidget = root.Find("ContentFrame/ContentBg/BaseInfoGroup/TabContentGroup/TabContent_CrewMatrix/RightGroup/AcquiredMatrixList").GetComponent<UIWidget>();
		moreMatrixInfoBtn = root.Find("ContentFrame/ContentBg/BaseInfoGroup/TabContentGroup/TabContent_CrewMatrix/RightGroup/MoreMatrixList/titleBg").GetComponent<UIButton>();
		arrowSprite = root.Find("ContentFrame/ContentBg/BaseInfoGroup/TabContentGroup/TabContent_CrewMatrix/TopGroup/arrowSprite").GetComponent<UISprite>();
	}
}
