//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for FormationItemWidget.
/// </summary>
public class FormationItemWidget : BaseView
{
	public UIEventTrigger eventTrigger;
	public UISprite icon;
	public UISprite indexSprite;
	public GameObject selectEffect;
	public UILabel nameLbl;
	public GameObject bgSprite;

	public void Setup (Transform root)
	{
	eventTrigger = root.GetComponent<UIEventTrigger>();
		icon = root.Find("icon").GetComponent<UISprite>();
		indexSprite = root.Find("bgSprite/indexSprite").GetComponent<UISprite>();
		selectEffect = root.Find("selectEffect").gameObject;
		nameLbl = root.Find("nameLbl").GetComponent<UILabel>();
		bgSprite = root.Find("bgSprite").gameObject;
	}
}
