//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for MissionCellView.
/// </summary>
public class MissionCellView : BaseView
{
	public UILabel DescriptionLabel_UILabel;
	public UILabel TypeLabel_UILabel;
	public UISprite BuoySprite_UISprite;
	public UIButton BgSprite_UIButton;

	public void Setup (Transform root)
	{
		DescriptionLabel_UILabel = root.Find("DescriptionLabel").GetComponent<UILabel>();
		TypeLabel_UILabel = root.Find("TypeLabel").GetComponent<UILabel>();
		BuoySprite_UISprite = root.Find("BuoySprite").GetComponent<UISprite>();
		BgSprite_UIButton = root.Find("BgSprite").GetComponent<UIButton>();
	}
}
