//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for MissionView.
/// </summary>
public class MissionView : BaseView
{
	public Transform AceGroup_Transform;
	public UIButton Button_UIButton;
	public Transform CurGroup_Transform;
	public UIGrid TabGrid_UIGrid;
	public UIScrollView ScrollView_UIScrollView;
	public UIGrid TypeGrid_UIGrid;
	public UILabel AceAcceptNPCLabel_UILabel;
	public UILabel AceDescriptionLabel_UILabel;
	public UILabel AceGradeLabel_UILabel;
	public UILabel AceTypeLabel_UILabel;
	public UILabel CurDescriptionLabel_UILabel;
	public UIButton CurItemBgSprite_UIButton;
	public UISprite CurIconSprite_UISprite;
	public UILabel CurSubmitNPCLabel_UILabel;
	public UILabel CurTargetLabel_UILabel;
	public UILabel CurTypeLabel_UILabel;
	public UIButton AceBtn_UIButton;
	public UIButton CurDropBtn_UIButton;
	public UIButton CurConveyBtn_UIButton;

	public void Setup (Transform root)
	{
		AceGroup_Transform = root.Find("AceGroup");
		Button_UIButton = root.Find("BgGroup/Button").GetComponent<UIButton>();
		CurGroup_Transform = root.Find("CurGroup");
		TabGrid_UIGrid = root.Find("TabGrid").GetComponent<UIGrid>();
		ScrollView_UIScrollView = root.Find("TypeView/ScrollView").GetComponent<UIScrollView>();
		TypeGrid_UIGrid = root.Find("TypeView/ScrollView/TypeGrid").GetComponent<UIGrid>();
		AceAcceptNPCLabel_UILabel = root.Find("AceGroup/AceAcceptNPCLabel").GetComponent<UILabel>();
		AceDescriptionLabel_UILabel = root.Find("AceGroup/AceDescriptionLabel").GetComponent<UILabel>();
		AceGradeLabel_UILabel = root.Find("AceGroup/AceGradeLabel").GetComponent<UILabel>();
		AceTypeLabel_UILabel = root.Find("AceGroup/AceTypeLabel").GetComponent<UILabel>();
		CurDescriptionLabel_UILabel = root.Find("CurGroup/CurDescriptionLabel").GetComponent<UILabel>();
		CurItemBgSprite_UIButton = root.Find("CurGroup/CurItemBgSprite").GetComponent<UIButton>();
		CurIconSprite_UISprite = root.Find("CurGroup/CurItemBgSprite/CurIconSprite").GetComponent<UISprite>();
		CurSubmitNPCLabel_UILabel = root.Find("CurGroup/CurSubmitNPCLabel").GetComponent<UILabel>();
		CurTargetLabel_UILabel = root.Find("CurGroup/CurTargetLabel").GetComponent<UILabel>();
		CurTypeLabel_UILabel = root.Find("CurGroup/CurTypeLabel").GetComponent<UILabel>();
		AceBtn_UIButton = root.Find("AceGroup/AceBtn").GetComponent<UIButton>();
		CurDropBtn_UIButton = root.Find("CurGroup/CurDropBtn").GetComponent<UIButton>();
		CurConveyBtn_UIButton = root.Find("CurGroup/CurConveyBtn").GetComponent<UIButton>();
	}
}
