//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for UseItemCell.
/// </summary>
public class UseItemCell : BaseView
{
	public UIButton RomeveBtn;
	public UILabel CountLabel;

	public void Setup (Transform root)
	{
		RomeveBtn = root.Find("RomeveBtn").GetComponent<UIButton>();
		CountLabel = root.Find("CountLabel").GetComponent<UILabel>();
	}
}
