//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for MiniMapView.
/// </summary>
public class MiniMapView : BaseView
{
	public UIButton CloseBtn;
	public UISprite BgSprite;
	public UITexture Texture;
	public GameObject HeroSprite;
	public GameObject WalkSprite;
	public BoxCollider Texture_BoxCollider;
	public GameObject SignPanel;

	public void Setup (Transform root)
	{
		CloseBtn = root.Find("CloseBtn").GetComponent<UIButton>();
		BgSprite = root.Find("BgSprite").GetComponent<UISprite>();
		Texture = root.Find("Texture").GetComponent<UITexture>();
		HeroSprite = root.Find("Texture/SignPanel/HeroSprite").gameObject;
		WalkSprite = root.Find("Texture/SignPanel/WalkSprite").gameObject;
		Texture_BoxCollider = root.Find("Texture").GetComponent<BoxCollider>();
		SignPanel = root.Find("Texture/SignPanel").gameObject;
	}
}
