//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for TabBtnWidget.
/// </summary>
public class TabBtnWidget : BaseView
{
	public UISprite btnBg;
	public UILabel btnLbl;

	public void Setup (Transform root)
	{
		btnBg = root.GetComponent<UISprite>();
		btnLbl = root.Find("btnLbl").GetComponent<UILabel>();
	}
}
