//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for ConsumerTipsView.
/// </summary>
public class ConsumerTipsView : BaseView
{
	public UIButton CloseButton;
	public UIGrid ItemCellGrid;
	public GameObject OptButtonPos;
	public UILabel TipsLabel;
	public UISprite ContentBg;

	public void Setup (Transform root)
	{
		CloseButton = root.Find("CloseButton").GetComponent<UIButton>();
		ItemCellGrid = root.Find("ContentBg/ItemCellGrid").GetComponent<UIGrid>();
		OptButtonPos = root.Find("ContentBg/OptButtonPos").gameObject;
		TipsLabel = root.Find("ContentBg/TipsLabel").GetComponent<UILabel>();
		ContentBg = root.Find("ContentBg").GetComponent<UISprite>();
	}
}
