
// Generated file. Do not edit.
// Generated By Gecko,if you need to edit it,extends it! 

//using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;


namespace com.baoyugame.kdts.core.modules.chat.dto
{  
  /** 聊天信息 */
  public class ChannelTalk 
  {
    // 当前频道
    public const int ChannelType_CurrentChannel = 0;
    // 世界频道
    public const int ChannelType_WorldChannel = 1;
    // 系统频道
    public const int ChannelType_SystemChannel = 2;
    // 公会频道
    public const int ChannelType_GuildChannel = 3;
    // 队伍频道
    public const int ChannelType_TeamChannel = 4;
    // 私聊频道
    public const int ChannelType_PrivalChannel = 5;

    /** 说话发起者ID */
    public long sayerId;
    
    /** 说话发起者昵称 */
    public string sayerName;
    
    /** 内容 */
    public string message;
    
    /** 频道类型，ChannelType */
    public int channelType;
    
    /** 听者ID */
	public long listenerId;
    
    /** 听者名称 */
    public string listenerName;
    
    /** 说话vip等级 */
    public int sayerVipLevel;
    
    /** 听vip等级 */
    public int listenerVipLevel;
    
    /** 发言时间 */
    public long time;
    
    /** 消息标识 */
    public string id;
    

  }

}
