//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for WarehouseWinUI.
/// </summary>
public class WarehouseWinUI : BaseView
{
	public UIButton CloseBtn;
	public GameObject WarehousePos;
	public GameObject BackpackPos;
	public GameObject WarehouseArrangeBtnPos;
	public GameObject BackpackArrangeBtnPos;
	public UIButton AddSilverBtn;
	public UILabel SilverValLbl;
	public UILabel SilverLbl;
	public UIButton AddCopperBtn;
	public UILabel CopperValLbl;
	public UILabel CopperLbl;

	public void Setup (Transform root)
	{
		CloseBtn = root.Find("bgGroup/CloseBtn").GetComponent<UIButton>();
		WarehousePos = root.Find("WarehousePos").gameObject;
		BackpackPos = root.Find("BackpackPos").gameObject;
		WarehouseArrangeBtnPos = root.Find("WarehouseArrangeBtnPos").gameObject;
		BackpackArrangeBtnPos = root.Find("BackpackArrangeBtnPos").gameObject;
		AddSilverBtn = root.Find("2_silver/bgSprite/valueBg/AddSilverBtn").GetComponent<UIButton>();
		SilverValLbl = root.Find("2_silver/bgSprite/valueBg/valLbl").GetComponent<UILabel>();
		SilverLbl = root.Find("2_silver/bgSprite/titleBg/titleLbl").GetComponent<UILabel>();
		AddCopperBtn = root.Find("1_copper/bgSprite/valueBg/AddCopperBtn").GetComponent<UIButton>();
		CopperValLbl = root.Find("1_copper/bgSprite/valueBg/valLbl").GetComponent<UILabel>();
		CopperLbl = root.Find("1_copper/bgSprite/titleBg/titleLbl").GetComponent<UILabel>();
	}
}
