//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

/// <summary>
/// Generates a safe wrapper for SatiationPropsUseView.
/// </summary>
public class SatiationPropsUseView : BaseView
{
	public UIEventTrigger BgEventTrigger;
	public UIGrid itemGrid;
	public UIButton useCopperBtn;
	public UILabel tipLbl;
	public UILabel btnLbl;
	public UIButton hintBtn;

	public void Setup (Transform root)
	{
		BgEventTrigger = root.Find("BgCollider").GetComponent<UIEventTrigger>();
		itemGrid = root.Find("ContentBg/itemGrid").GetComponent<UIGrid>();
		useCopperBtn = root.Find("ContentBg/useCopperBtn").GetComponent<UIButton>();
		tipLbl = root.Find("ContentBg/useCopperBtn/tipLbl").GetComponent<UILabel>();
		btnLbl = root.Find("ContentBg/useCopperBtn/btnLbl").GetComponent<UILabel>();
		hintBtn = root.Find("ContentBg/useCopperBtn/hintBtn").GetComponent<UIButton>();
	}
}
